### ISSUE TITLE
PHP 8: Test that the agent works with frameworks that support PHP 8

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#106]
We need to spot test that the agent works with frameworks that support PHP 8.0 while keeping in mind that support may still be in progress (e.g., Drupal) with these frameworks. With the exception of Drupal, this can be done in conjunction with the soak test run/updates. 

- Drupal
  - Check-in on the progress of this. 
- Laravel
  - Here’s the PHP 8 support [PR](https://github.com/laravel/framework/pull/33388). Laravel 6.x will support PHP 8.0.  Laravel 8 supports PHP 8.
- Symfony
  - 5.2 [announcement post](https://symfony.com/blog/new-in-symfony-5-2-php-8-attributes).
- Wordpress
  - Version 5.6 (12/8/2020 release date) will add support for PHP 8.0 but will do so in a backward-compatible way. WordPress supports PHP 5.6.20 and above. See their [call for testing](https://make.wordpress.org/core/2020/10/06/call-for-testing-php-8-0/) post.
- Slim (used by the PHP 7.4 agent soak test)
  - Version 4.x will support PHP 8. See this [GitHub issue](https://github.com/slimphp/Slim/issues/2977).

**Comment by zsistla** [comment]
This ticket is part of issue #34.

**Comment by Fahmy-Mohammed** [comment]
Summary of framework testing found [here](https://docs.google.com/document/d/1NUQ-WPYv92r5mFYG6lRoe-XlsYK6Cws-TeXzhm8-TnU/edit#)
