### ISSUE TITLE
PHP 8: Ensure all integration tests run

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#107]
Currently, a large number of our integration tests are failing on PHP 8.0. We need to fix these failures and ensure that all integration tests pass. Please see the [MMF doc](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.7evzjypgrzid) for a list of the changes that happened in PHP 8.0 that need to be accounted for in our tests. This will involve:

- Fixing all integration tests
- Ensuring the integration runner is updated for PHP 8.0 functionality. Account for any deprecated functions that have been removed in PHP 8.0
- Add the integration tests to the release build process (similar to the [Jenkins style](https://source.datanerd.us/php-agent/newrelic-php-agent-internal/blob/master/hudson/test.sh), but added to the GHA [release build script](https://github.com/newrelic/newrelic-php-agent/blob/dev/.github/docker/linux/release_build.sh))
- Re-enable the integration tests in [GHA](https://github.com/newrelic/newrelic-php-agent/blob/dev/.github/docker/linux/pr_build.sh#L146) and in the [Jenkins PR builder job](https://source.datanerd.us/php-agent/newrelic-php-agent-internal/blob/master/hudson/build-pull-request.sh#L156) (for PHP 8.0)

**Comment by zsistla** [comment]
This ticket is part of issue #34.

**Comment by Fahmy-Mohammed** [comment]
This is fixed in #121, #124, and [20](https://source.datanerd.us/php-agent/newrelic-php-agent-internal/pull/20). The drupal 6 & 7 integration tests are skipped since drupal 6/7 do not support PHP 8
