### ISSUE TITLE
PHP 8: Investigate and fix the Valgrind issues

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#108]
The axiom and agent Valgrind unit tests are currently disabled on PHP 8.0 due to some issues on both 32 and 64 bit OSs. See the [MMF doc](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.v2mcfrbllohv) and #105 for more info. This will involve:

- Investigate and fix the Valgrind memory issues
- Re-enable the Valgrind unit tests in [GHA](https://github.com/newrelic/newrelic-php-agent/blob/dev/.github/docker/linux/pr_build.sh#L75)

**Comment by zsistla** [comment]
This ticket is part of issue #34.

**Comment by zsistla** [comment]
Fixed by PRs #118 and #119 .
