### ISSUE TITLE
PHP 8: Multiverse tests run

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#109]
After we've verified the spot checks on other frameworks (#106) we should ensure that the [multiverse tests](https://source.datanerd.us/php-agent/multiverse) can run on PHP 8.0. This will involve:

- Running and fixing any issues related to PHP 8.0
- Skip any library versions that do not support PHP 8.0. This can be done using the `/*SKIPIF*/`  directive. Refer to other tests to see how this is done.
- Ensure the multiverse tests run through without error.

**Comment by zsistla** [comment]
This ticket is part of issue #34.
