### ISSUE TITLE
PHP 8: Soak Test Run

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#110]
We need to perform a soak test run and ensure they run through with PHP 8.0. This will build on the work done in #63 and should be done simultaneously with the framework spot checks. Items left over from #63:

- Slim (current run complains of unlinked classes, this may invalidate results. investigate and fix, if necessary)
- Remove the Valgrind-processor from the soak test runs, replace it with a script to fail if Valgrind detects any issues
- Output the raw (non-XML) Valgrind results at the end of each run
- Merge test-apps PR with PHP 8.0 related changes, update the 8.0 inward singing job to point to the dev branch

For the Soak test runs on Jenkins, a test build might need to be cut. The same is needed for the xPlatform tests (#111). Coordinate with whoever is working on that to avoid multiple test builds.

**Comment by joshuabenuck** [comment]
These two bullets are addressed in the latest version of PR 41 in the test-apps repo:
* Remove the Valgrind-processor from the soak test runs, replace it with a script to fail if Valgrind detects any issues
* Output the raw (non-XML) Valgrind results at the end of each run

See the PR for more details.

**Comment by zsistla** [comment]
This ticket is part of issue #34.

**Comment by kneitinger** [comment]
Internal test updates validated and merged.
