### ISSUE TITLE
PHP 8: xPlatform Tests

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#111]
Before we get to the release process, let’s confirm that the [xPlatform](https://phpagent-build.pdx.vm.datanerd.us/job/QAPhpAutotest_xPlatform/) tests run through without any errors. This will involve:
- Cut a test build and perform a run with the PHP 8 changes included. A test build might be needed for #110. Coordinate with whoever works on that to avoid multiple test builds.
- Fix any errors that are encountered

**Comment by zsistla** [comment]
This ticket is part of issue #34.

**Comment by joshuabenuck** [comment]
xPlatform # 162 run on 04/14 passed. Closing this ticket.
