### ISSUE TITLE
PHP 8: Performance tests

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#112]
We need to benchmark the performance of PHP8 against the previous PHP versions. You can use our performance tests for this but let's investigate if there is another way we can get a more detailed benchmark of this.

**Comment by zsistla** [comment]
This ticket is part of issue #34.

**Comment by zsistla** [comment]
No performance changes indicated by test run.
===================================================================
Benchmark phpinfo
===================================================================
I      disabled  9.13.0.270  9.14.0.290  9.15.0.293  9.16.0.295  9.17.0.295
1/10   1059.68   436.53      435.31      436.00      436.90      435.21
2/10   1083.42   436.78      435.65      435.71      436.05      435.65
3/10   1057.92   437.46      436.36      435.27      434.85      435.78
4/10   1066.19   437.59      435.57      435.71      437.76      436.01
5/10   1068.57   436.40      435.83      435.68      436.07      435.19
6/10   1063.53   437.19      436.81      435.46      435.35      436.57
7/10   1093.01   436.85      434.95      435.40      435.37      437.07
8/10   1092.02   435.93      437.55      436.25      436.92      435.38
9/10   1058.92   436.94      436.37      436.46      435.68      434.06
10/10  1053.75   437.23      435.21      435.57      435.43      435.95
===================================================================
Benchmark segments
===================================================================
I      disabled  9.13.0.270  9.14.0.290  9.15.0.293  9.16.0.295  9.17.0.295
1/10   358.52    224.23      224.63      229.63      229.32      229.64
2/10   361.26    224.22      228.29      227.05      226.96      227.23
3/10   359.94    226.04      225.55      227.06      223.71      226.33
4/10   359.14    226.22      227.05      227.41      227.95      227.12
5/10   359.41    228.54      225.90      227.47      228.92      225.33
6/10   360.34    226.06      225.98      228.11      223.85      228.89
7/10   361.12    228.61      227.54      224.60      223.79      224.53
8/10   362.52    228.06      226.83      225.32      227.67      218.38
9/10   358.56    227.95      226.48      227.02      227.56      224.65
10/10  361.10    227.99      225.55      224.91      229.33      229.82
===================================================================
Benchmark laravel
===================================================================
I      disabled  9.13.0.270  9.14.0.290  9.15.0.293  9.16.0.295  9.17.0.295
1/10   13.09     12.11       12.10       12.08       12.07       12.06
2/10   13.05     12.05       12.12       12.10       12.08       12.09
3/10   13.02     12.08       12.11       12.09       12.07       12.09
4/10   13.07     12.09       12.10       12.09       12.04       12.07
5/10   13.05     12.06       12.06       12.07       11.98       12.08
6/10   13.04     12.11       12.08       12.11       12.08       12.09
7/10   13.03     12.07       12.11       12.08       12.09       12.09
8/10   13.03     12.08       12.10       12.09       12.06       12.04
9/10   13.05     12.09       12.08       12.10       12.08       12.07
10/10  13.06     12.07       12.08       12.08       12.06       12.07

===================================================================
Benchmark wordpress
===================================================================
I      disabled  9.13.0.270  9.14.0.290  9.15.0.293  9.16.0.295  9.17.0.295
1/10   7.64      6.90        6.88        6.87        6.90        6.89
2/10   7.64      6.91        6.89        6.88        6.89        6.90
3/10   7.64      6.89        6.90        6.90        6.89        6.91
4/10   7.64      6.90        6.91        6.88        6.90        6.91
5/10   7.65      6.89        6.91        6.89        6.90        6.89
6/10   7.65      6.88        6.90        6.89        6.88        6.88
7/10   7.64      6.87        6.90        6.90        6.90        6.88
8/10   7.63      6.90        6.91        6.90        6.89        6.90
9/10   7.66      6.90        6.89        6.90        6.90        6.90
10/10  7.65      6.88        6.89        6.89        6.90        6.89

**Comment by zsistla** [comment]
PHP 8 Benchmark performance tests:
```
php_1    | ===================================================================
php_1    | Benchmark phpinfo
php_1    | ===================================================================
php_1    | I      disabled  9.17.0.297
php_1    | 1/10   1193.18   497.42
php_1    | 2/10   1215.63   495.24
php_1    | 3/10   1236.07   497.74
php_1    | 4/10   1215.67   496.17
php_1    | 5/10   1215.56   489.56
php_1    | 6/10   1211.43   495.15
php_1    | 7/10   1212.86   496.01
php_1    | 8/10   1214.82   495.48
php_1    | 9/10   1216.31   495.84
php_1    | 10/10  1208.53   494.85
php_1    |
php_1    | ===================================================================
php_1    | Benchmark segments
php_1    | ===================================================================
php_1    | I      disabled  9.17.0.297
php_1    | 1/10   393.40    237.62
php_1    | 2/10   393.36    236.43
php_1    | 3/10   398.63    237.20
php_1    | 4/10   394.97    234.43
php_1    | 5/10   394.12    238.15
php_1    | 6/10   396.00    237.31
php_1    | 7/10   394.33    235.77
php_1    | 8/10   393.92    238.61
php_1    | 9/10   392.34    232.24
php_1    | 10/10  390.33    235.76
php_1    |
```

**Comment by zsistla** [comment]
Performance tests are comparable with previous versions of the agent running on PHP 7.4.

```
php_1    |
php_1    | ===================================================================
php_1    | Benchmark script phpinfo
php_1    | ===================================================================
php_1    | I disabled 9.13.0.270 9.14.0.290 9.15.0.293 9.16.0.295 9.17.0.297
php_1    |  1/10 1237.27 503.95 503.81 503.29 503.76 504.37
php_1    |  2/10 1245.48 503.54 505.35 504.52 505.22 503.40
php_1    |  3/10 1255.48 503.92 503.01 503.68 504.58 503.33
php_1    |  4/10 1240.58 504.49 503.56 503.32 506.59 503.00
php_1    |  5/10 1234.93 504.06 504.96 503.40 504.29 503.19
php_1    |  6/10 1242.19 502.87 502.84 502.49 504.73 500.47
php_1    |  7/10 1245.98 501.80 504.00 503.41 507.91 503.00
php_1    |  8/10 1248.54 504.41 504.70 503.37 504.82 503.14
php_1    |  9/10 1245.99 503.74 502.72 504.20 504.18 505.02
php_1    |  10/10 1250.70 504.77 503.52 502.53 505.11 503.70
php_1    |
php_1    | ===================================================================
php_1    | Benchmark script segments
php_1    | ===================================================================
php_1    | I disabled 9.13.0.270 9.14.0.290 9.15.0.293 9.16.0.295 9.17.0.297
php_1    |  1/10 397.61 231.11 231.45 230.30 229.78 231.21
php_1    |  2/10 399.73 229.91 232.90 228.53 229.11 231.68
php_1    |  3/10 398.87 227.29 234.65 227.48 229.73 232.97
php_1    |  4/10 402.03 231.75 230.26 232.66 230.02 232.66
php_1    |  5/10 401.60 231.51 232.52 229.67 230.67 232.63
php_1    |  6/10 399.51 229.84 232.40 232.12 228.62 232.35
php_1    |  7/10 401.05 232.19 217.37 232.74 229.09 231.50
php_1    |  8/10 402.62 229.15 232.33 233.61 231.29 232.56
php_1    |  9/10 401.08 230.24 232.66 229.14 227.72 232.41
php_1    |  10/10 400.01 230.53 232.12 233.42 230.74 232.02
php_1    |
php_1    | ===================================================================
php_1    | Benchmark script laravel
php_1    | ===================================================================
php_1    | I disabled 9.13.0.270 9.14.0.290 9.15.0.293 9.16.0.295 9.17.0.297
php_1    |  1/10 14.02 12.89 12.87 12.86 12.88 12.85
php_1    |  2/10 14.05 12.85 12.90 12.90 12.86 12.86
php_1    |  3/10 14.03 12.89 12.86 12.87 12.81 12.89
php_1    |  4/10 14.02 12.89 12.86 12.89 12.87 12.84
php_1    |  5/10 13.99 12.89 12.88 12.87 12.87 12.84
php_1    |  6/10 14.01 12.87 12.87 12.88 12.87 12.88
php_1    |  7/10 14.04 12.91 12.83 12.82 12.88 12.86
php_1    |  8/10 13.96 12.90 12.89 12.89 12.90 12.87
php_1    |  9/10 14.03 12.88 12.91 12.86 12.84 12.87
php_1    |  10/10 14.02 12.87 12.90 12.88 12.86 12.87
php_1    |
php_1    | ===================================================================
php_1    | Benchmark script wordpress
php_1    | ===================================================================
php_1    | I disabled 9.13.0.270 9.14.0.290 9.15.0.293 9.16.0.295 9.17.0.297
php_1    |  1/10 8.50 7.64 7.63 7.64 7.62 7.65
php_1    |  2/10 8.56 7.64 7.58 7.65 7.65 7.63
php_1    |  3/10 8.56 7.64 7.62 7.63 7.60 7.62
php_1    |  4/10 8.53 7.65 7.62 7.60 7.67 7.65
php_1    |  5/10 8.55 7.65 7.64 7.64 7.65 7.62
php_1    |  6/10 8.57 7.65 7.62 7.67 7.66 7.59
php_1    |  7/10 8.50 7.66 7.65 7.67 7.66 7.65
php_1    |  8/10 8.59 7.60 7.66 7.64 7.60 7.66
php_1    |  9/10 8.56 7.63 7.63 7.64 7.65 7.64
php_1    |  10/10 8.57 7.66 7.64 7.66 7.64 7.64
```
