### ISSUE TITLE
Symfony5 support

### ISSUE THREAD

**Issue by b-viguier** [newrelic/newrelic-php-agent#113]
## Summary

The NR php agent supports [Symfony framework](https://symfony.com/) from version [1 to 4](https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration#inivar-framework). Since version 5, some breaking changes may prevent NR extension to report all expected information. Is SF5 support in your Roadmap?

## Desired Behavior

* Auto-detect SF5 framework usage
* Report exceptions

## Possible Solution

SF5 replaces the `ExceptionListener` class by `ErrorListener` (see [UPGRADE](https://github.com/symfony/symfony/blob/adbb34115c82690ab178eb9599891f4352d0ac20/UPGRADE-5.0.md#httpkernel) instructions). Unfortunately, NR extension is explicitly looking for `ExceptionListener` class, to wrap it and report exceptions.
https://github.com/newrelic/newrelic-php-agent/blob/3f93ee47f80703d46d8fccd53be7d6b80361a594/agent/fw_symfony4.c#L184-L187
By detecting SF5 framework, we could change wrapped function… if I understand the code correctly 😅 

## Additional context

None.

Thanks for your work 👍

**Comment by joaojacome** [comment]
IMO the framework-specific functions should be delegated to a composer package, instead of locking the frameworks in the extension.

**Comment by piotrantosik** [comment]
Hi, anyone tries setup newrelic with symfony 5? It's works when I set `newrelic.framework = "symfony4"`?
Right now I use with `newrelic.preload_framework_library_detection = false` but in this setup I don't see proper transactions.

**Comment by b-viguier** [comment]
@piotrantosik We are using https://github.com/ekino/EkinoNewRelicBundle, it's a little redundant with built-in framework support, but at least transaction names are correctly handled

**Comment by Ak-x** [comment]
Closing this issue per https://github.com/newrelic/newrelic-php-agent/pull/256
