### ISSUE TITLE
Rename APT package

### ISSUE THREAD

**Issue by foxycode** [newrelic/newrelic-php-agent#116]
## Summary

I think that `newrelic-php5` package name is little bit outdated.

## Desired Behavior

It would be ideal, if there was more packages containing only single version same way as on [Ubuntu PHP PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php).

## Possible Solution

Simple solution would be name package as `php-newrelic` which is default for many php packages.

**Comment by jodeev** [comment]
We totally understand where you're coming from. We agree with your points. 

Once we are touching this infrastructure, we intend to look into making this change. Right now, due to both internal and external factors, this is infeasible.

Thank you so much for your feedback.
