### ISSUE TITLE
Can you host an install script that used to be on docs?

### ISSUE THREAD

**Issue by mmfred** [newrelic/newrelic-php-agent#117]
Hi there - when we moved the docs to GitHub, we left behind this install script, [attached](url
[PHP-manual-install-script-master_1.zip](https://github.com/newrelic/newrelic-php-agent/files/6086880/PHP-manual-install-script-master_1.zip)
)

Would you be willing to host this script here, and then we can link from the docs? 

That way, it might encourage users to come to this repo, and it runs a better chance of being kept up-to-date. 

I'm happy to answer questions. If you do decide to host it, shoot me a link so I can update the doc that references it: 
https://docs-dev.newrelic.com/docs/agents/php-agent/advanced-installation/php-agent-installation-non-standard-php-advanced#manual (note that it's the broken link in the second paragraph of this section)

Thanks!

**Comment by joshuabenuck** [comment]
We plan on removing the reference to the install script and the info box right after that also mentions it.

**Comment by mmfred** [comment]
@joshuabenuck - thanks for that info. two questions:

Can we go ahead and remove this info from the docs now?

Also, there's a page in docs called, [Use the newrelic-install script for PHP ](https://docs-dev.newrelic.com/docs/agents/php-agent/advanced-installation/use-newrelic-install-script-php) - it doesn't appear to link to this script. Is that okay to leave as is?

**Comment by kneitinger** [comment]
Hi @mmfred

**Comment by kneitinger** [comment]
Hi @mmfred,

You can go ahead and remove that info, thanks! The `newrelic-install` script is still relevant to our agent installation, so it should indeed be left as is.

Take care!
