### ISSUE TITLE
PHP 8: Validate all applicable integration tests on PHP 8

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-agent#129]
This is part of #34 and is a continuation of #107.

Our CI systems do not run all tests on all OS / PHP version combinations. Since this is the first release that will support PHP 8, we should run all applicable integration tests against a PHP 8 agent build.

Tasks:
* (done) Compare the lists of skipped tests on the latest libc (CentOS), alpine (musl), and FreeBSD integration PHP 8 PR runs. Come up with a list of integration tests skipped on all of these configurations.
* Ensure that all of the skipped tests are run at least once manually w/ PHP 8.0 on a dev system or an AMI.
* Fix any tests that are failing.

List of tests to run:
* predis (5 tests not run anywhere)
* memcache (8 tests)
* redis (2 known failing tests): extension was already upgraded on the 64-bit system
* lasp (5 tests)
* http (7 tests)
* memcached (10 tests) - official PHP 8 support not released, but needed changes are in their dev branch. Should we test the dev branch?
* mongo (2 tests) - N/A not supported on PHP 8.0 (mongodb extension is, but we don’t support it)
* mysql (5 tests)
* mysqli (27 tests)
* pdo (15 tests)
* pgsql (10 tests)
* sqlite (10 tests)
* sqlitedatabase (5 tests)
* uopz - N/A will be handled in a separate ticket post release
* misc
  - tests/regression/test_php_1179_pdo_options_crash.php # skip: SQLSTATE[HY000] [2002] No such file or directory
misc
  - tests/integration/events/test_database_duration.php # skip: SQLSTATE[HY000] [2002] No such file or directory
  - tests/integration/external/file_get_contents/test_cat_and_synthetics_disabled.php # skip: env vars required

**Comment by zsistla** [comment]
For `redis` see PR #136 
For `mysqli` see PR #137

**Comment by zsistla** [comment]
See PR #134

**Comment by joshuabenuck** [comment]
Here are the results of the tests investigation:
* predis, redis, mysqli, pgsql, and uopz all had some test bit rot.
* lasp, pdo run successfully, but will need to be updated if we want to update the version of mysql on the build nodes.
* memcache (8 tests)
* http - N/A for php 8. We only support an old version of the this extension.
* memcached - all tests passed using the latest dev changes of the extension.
* sqlite - N/A for php 8.
* sqlitedatabase - all pass
* misc - one not applicable, the other two pass.

Closing this now that PRs #134, #136, and #137 are closed.
