### ISSUE TITLE
PHP8: Documentation updates to reflect PHP 8 support

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#133]
We need to update our documentation to reflect our upcoming support of PHP 8. This includes:

- [x] [PHP releases](https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements/#php-release)
- [x] [Frameworks](https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements/#frameworks)
- [x] [Agent Installation](https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-aws-linux-redhat-centos/#install)
- [x] [Development Guide](https://github.com/newrelic/newrelic-php-agent/blob/main/docs/development.md#php)
- [x] [Release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/) + [GitHub release](https://github.com/newrelic/newrelic-php-agent/releases)
- [ ] Explorers hub blog post - (optional) not required for release.

**Comment by Fahmy-Mohammed** [comment]
Docs update [PR](https://github.com/newrelic/docs-website/pull/1894)

**Comment by zsistla** [comment]
Part of #35 .
