### ISSUE TITLE
9.17: Stability Testing

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#140]
Part of #35.

Drive traffic through application using popular PHP frameworks. Check for memory leaks and violations with valgrind.

Tests can be started via the Inward Singing Jenkins job.

**Comment by Fahmy-Mohammed** [comment]
Verified in [this](https://phpagent-build.pdx.vm.datanerd.us/job/php-inward-singing-top/26/) Jenkins run. The PHP 7.2 [run](https://phpagent-build.pdx.vm.datanerd.us/job/php-inward-singing-parallel-7-2/37/) had some valgrind errors unrelated to the agent. Some suppressions for those errors will be added in a follow-up PR.
