### ISSUE TITLE
9.17.1: Cross-Platform Installation and Sanity Testing 

### ISSUE THREAD

**Issue by Fahmy-Mohammed** [newrelic/newrelic-php-agent#151]
Run the xPlatform Jenkins job.

Part of #150

**Comment by RichVanderwal** [comment]
Interesting -- that "agent version mismatch" isn't a false failure. It's actually one of the more important parts of the xPlatform test.

**Comment by Fahmy-Mohammed** [comment]
Passed in [this](https://phpagent-build.pdx.vm.datanerd.us/view/QA/job/QAPhpAutotest_xPlatform/175/) run
