### ISSUE TITLE
Virtuoso: Second phase, target environment support

### ISSUE THREAD

**Issue by kneitinger** [newrelic/newrelic-php-agent#160]
This epic builds off the work done in #93 to taget more environments than only Debian + FPM/nginx.  By the end of this work, systems running Apache or Nginx on Debian or RHEL (or their respective deriviates) can have the PHP Agent installed and configured via `newrelic install` through the [Open Install Library](https://github.com/newrelic/open-install-library)

**Comment by joshuabenuck** [comment]
Rolling this into #93.
