### ISSUE TITLE
Virtuoso: Incorporate silent mode in the php agent install recipe.

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#165]
Silent mode needs to be incorporated similar to [this](https://github.com/newrelic/open-install-library/blob/e7347282f607e079f528d8199b678f29dbeb4fcb/recipes/newrelic/apm/dotNet/linux-systemd.yml#L71). 

Done as one ticket so it is consistent across the tasks.

Part of MMF issue #93 .

**Comment by joshuabenuck** [comment]
Fahmy tested this and found it to be working without the need for any additional recipe modification. The automated deploy configs from open-install-library PR [424](https://github.com/newrelic/open-install-library/pull/424) further demonstrate that this working.
