### ISSUE TITLE
Virtuoso: use virtuoso error codes and cleanup on exit.

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#166]
Add applicable virtuoso [error exit codes](https://github.com/newrelic/open-install-library/blob/main/docs/error-codes.md) ~and ensure cleanup occurs before exiting by calling the `delete_shared` task.~ (It's not possible to call a task from another task, so we have decided to let a successful run do the cleanup).  Have consistent usage/wording across tasks.

Part of #93.

**Comment by joshuabenuck** [comment]
Implemented by open-install-library PR [404](https://github.com/newrelic/open-install-library/pull/404).
