### ISSUE TITLE
Virtuoso: Verify required tools are installed on system

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#167]
Verify required tools (sed, awk, etc) exist on the system.  Similar to [this](https://github.com/newrelic/open-install-library/blob/e7347282f607e079f528d8199b678f29dbeb4fcb/recipes/newrelic/apm/dotNet/linux-systemd.yml#L102) or [this](https://github.com/newrelic/open-install-library/blob/f10c87fd0aa954080c350f63187d8ca7183e5db3/recipes/newrelic/infrastructure/debian.yml#L46).

Part of #93.

**Comment by joshuabenuck** [comment]
Other checks to consider:
* Is this being run under `sudo`? We sudo to `$SUDO_USER` at one point in the recipe.
* Is `systemd` present? We use it to restart services.

Some other thoughts about this one:
* Ensuring that we use a unique return code for each failure condition would allow us to determine how common each is.
* Some of these error conditions could be corrected by installing or bundling additional packages.
* If a correctable error condition occurs commonly enough, we should consider automating the fix (possibly after prompting the user).

**Comment by joshuabenuck** [comment]
Implemented by [open-install-library PR 404](https://github.com/newrelic/open-install-library/pull/404).
