### ISSUE TITLE
PHP: improve permissions related issues when installing from tarball

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#168]
The current way install and daemon/agent initialization works can lead to some permissions related unexpected behavior (see details below).

Possible remedies/recommendations:
1) installation could create the `newrelic.ini` files with broader read/write permissions; at a minimum give `$SUDO_USER` permission to edit
2) installation could create the log directories with broader read/write permissions; at a minimum give `$SUDO_USER` permissions and/or create stub log files that `$SUDO_USER` (although just creating the stub files won’t help if the default is not used).
3) document that if there are two newrelic.ini’s that are using the same daemon socket, then having different daemon log file locations is NOT recommended and will in fact not work as expected.  Daemon logs will only be sent to the logfile of the first daemon started.

**Details:**

We specify running install as root: https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-aws-linux-redhat-centos/#download-rpm

**Setup:**
cd /tmp
wget http://download.newrelic.com/php_agent/archive/9.17.1.301/newrelic-php5-9.17.1.301-linux.tar.gz
tar xzf newrelic-php5-9.17.1.301-linux.tar.gz
sudo NR_INSTALL_USE_CP_NOT_LN=1 ./newrelic-php5-9.17.1.301-linux/newrelic-install install

Running as local user ubuntu who has sudo privileges.

**First observations:**
1) Since we ran the install as `sudo`, I need to `sudo vi` to edit the ini files.
2) Since we ran the install as `sudo`, I need to manually create log files in the /var/log/newrelic directory and `chmod` the read/write permissions for the php-cli to even be able to start the agent/daemon.  Starting the web first has no issues because the apache service is restarted as root and the daemon runs as root, so it has permission as root to create/read/write the php_agent and daemon log files.  Once the daemon is running, if the php-cli uses the same socket, it will report data to NR1 and the daemon log associated with running daemon (not the one configured in the cli newrelic.ini) will record logs, but it the agent won’t log to the php agent log without `chmod`ing the permissions.  In cases below regarding php-cli, the ini files have been manually created/chmod-ed. 

**Case:**
1) Different log files, same socket
	cli ini /etc/php/7.2/cli/conf.d/newrelic.ini: 
	* points to Logs: points to php_agent_cli.log, newrelic-daemon-cli.log *
	* points to socket: @newrelic
	* points to app name: PHP Application virtuoso 1
   	web ini /etc/php/7.2/apache2/conf.d/newrelic.ini: 
	* points to Logs: php_agent.log, newrelic-daemon.log 
	* points to socket: @newrelic 
	* points to app name: PHP Application virtuoso apache 1

	A) manually create the log files, add permissions, then start cli first:
	* Daemon is started as local user `ubuntu`
	* cli data shows up in NR1, cli agent data logs to php_agent-cli.log, cli 	daemon data logs to newrelic-daemon-cli.log
	* Restart the apache server, daemon is still running as `ubuntu`
	* load web page
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon-cli.log

	*Change the web app name to PHP Application virtuoso apache 1, restart the apache server

	* Restart the apache server, daemon is still running as `ubuntu`
	* load web page
	* the change is recognized
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon-cli.log
	* cli data shows up in NR1, cli agent data logs to php_agent-cli.log, cli daemon data logs to newrelic-daemon-cli.log

	B) kill the daemon, restart the apache server first.

	* daemon is running as `root`
	* load web page
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log
	* run cli
	* cli data shows up in NR1, cli agent data logs to php_agent-cli.log, cli daemon data logs to newrelic-daemon.log

	* Change the cli app name to PHP Application virtuoso apache 2

	* run the php-cli
	* daemon is still running as `root`
	* the app name change is recognized
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon-cli.log
	* cli data shows up in NR1, cli agent data logs to php_agent-cli.log, cli daemon data logs to newrelic-daemon.log

2) Same logs files, same socket
	cli ini /etc/php/7.2/cli/conf.d/newrelic.ini: 
	* points to Logs: points to php_agent_cli.log, newrelic-daemon-cli.log *
	* points to socket: @newrelic
	* points to app name: PHP Application virtuoso 3
   	Web ini /etc/php/7.2/apache2/conf.d/newrelic.ini: 
	* points to Logs: php_agent.log, newrelic-daemon.log 
	* points to socket: @newrelic 
	* points to app name: PHP Application virtuoso apache 3

	A) start php-cli first
	* start php-cli 
	* php-cli is not able to start daemon, because it doesn’t have permission to var/log/newrelic.
	* create/chmod the logs
	* php-cli daemon is started running as `ubuntu` on socket @newrelic
	* cli data shows up in NR1, cli agent logs to php_agent.log as the permissions were already modified, cli daemon data logs to newrelic-daemon.log
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log

	* Change the cli app name to PHP Application virtuoso apache 4

	* run the php-cli
	* daemon is running as `root`
	* the app name change is recognized
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon-cli.log
	* cli data shows up in NR1, cli agent logs to php_agent.log as the permissions were already modified, cli daemon data logs to newrelic-daemon.log

	B) restart the apache server first
	* daemon is running as `root`
	* load web page
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log
	* run cli
	* cli data shows up in NR1, cli agent initially will NOT log to php_agent.log as it has insufficient permissions but if chmod the log it will start reporting, cli daemon data logs to newrelic-daemon.log

	* Change the cli app name to PHP Application virtuoso apache 4

	* run the php-cli
	* daemon is running as `root`
	* the app name change is recognized
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon-cli.log
	* cli data shows up in NR1, cli agent logs to php_agent.log as the permissions were already modified, cli daemon data logs to newrelic-daemon.log

3) Same log files, different sockets
	cli ini /etc/php/7.2/cli/conf.d/newrelic.ini: 
	* points to Logs: points to php_agent_cli.log, newrelic-daemon-cli.log *
	* points to socket: @newrelic-cli
	* points to app name: PHP Application virtuoso 3
   	Web ini /etc/php/7.2/apache2/conf.d/newrelic.ini: 
	* points to Logs: php_agent.log, newrelic-daemon.log 
	* points to socket: @newrelic 
	* points to app name: PHP Application virtuoso apache 3

	A) start php-cli first (must manually create log files and chmod)
	* daemon is running as `ubuntu` on socket @newrelic-cli
	* cli data shows up in NR1, cli agents logs to php_agent.log , cli daemon data logs to newrelic-daemon.log
	* restart apache2
	* web-daemon is running as `root` on socket @newrelic
	* load web page
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log

	* Change the cli/web app names

	* restart apache2
	* run the php-cli
	* web-daemon is running as `root` on socket @newrelic
	* load web page
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log
	* cli data shows up in NR1, cli agent logs to php_agent.log , cli daemon data logs to newrelic-daemon.log
	* nr1 reports new app name w/data for both web/cli

	
	A) start web / apache first.
	* daemon is running as `root` on socket @newrelic
	* start php-cli 
	* php-cli is not able to start daemon, even on the different socket, because it doesn’t have permission to /var/log/newrelic/newrelic-daemon.log.
	* chmod the logs
	* php-cli daemon is started running as `ubuntu` on socket @newrelic-cli
	* cli data shows up in NR1, cli agents logs to php_agent.log , cli daemon data logs to newrelic-daemon.log
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log

	* Change the cli/web app names

	* restart apache2
	* run the php-cli
	* web-daemon is running as `root` on socket @newrelic
	* load web page
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log
	* cli data shows up in NR1, cli agent logs to php_agent.log , cli daemon data logs to newrelic-daemon.log
	* nr1 reports new app name w/data for both web/cli

	
	B) start php/cli first.
	* start php-cli 
	* php-cli is not able to start daemon, even on the different socket, because it doesn’t have permission to /var/log/newrelic/newrelic-daemon.log.
	* create/chmod the logs
	* php-cli daemon is started running as `ubuntu` on socket @newrelic-cli
	* restart the apache server
	* web daemon is running as `root` on socket @newrelic
	* cli data shows up in NR1, cli agents logs to php_agent.log , cli daemon data logs to newrelic-daemon.log
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log

	* Change the cli/web app names

	* restart apache2
	* run the php-cli
	* web-daemon is running as `root` on socket @newrelic
	* load web page
	* web data shows up in NR1, web agent data logs to php_agent.log, web daemon data logs to newrelic-daemon.log
	* cli data shows up in NR1, cli agent logs to php_agent.log , cli daemon data logs to newrelic-daemon.log
	* nr1 reports new app name w/data for both web/cli

**Comment by joshuabenuck** [comment]
Do we explicitly set the permissions on the log files or do we defer to the OS (and the configured `umask`) for the log file / daemon socket permissions? Does changing the `umask` to be more restrictive introduce any additional failures (like with being able to use the daemon socket)?

**Comment by zsistla** [comment]
We don't explicitly set the permissions currently.  If going through the agent installation as set above(i.e., download tar, unzip, run), a non-root user doesn't have access to the `log/newrelic` dir.  If it had permissions, it would be able to create the logs.  I'm not sure if there is different behavior if installing via `apt-get`.

**Comment by zsistla** [comment]
Related issue: https://stackoverflow.com/questions/68444120/dockerfile-chown-is-being-overwritten
