### ISSUE TITLE
Virtuoso: Make all messaging to the user consistent and visible.

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#169]
All messaging to the user should be consistent and visible.
For example [this](https://github.com/newrelic/open-install-library/blob/ce80d0720a08a5f2e75d91cceb3f039a9eb51010/recipes/newrelic/apm/php-agent/php.yml#L144) should look more like [this](https://github.com/newrelic/open-install-library/blob/e7347282f607e079f528d8199b678f29dbeb4fcb/recipes/newrelic/apm/dotNet/linux-systemd.yml#L293).

Additionally anything that produces output that doesn't need to be shown to the user should be sent to [null](https://github.com/newrelic/open-install-library/pull/359/files#diff-a34d073b4d6764ad6be1fd33e6ba607dda0e84ec50777ac5255c838b4904f5c9R179).

**Comment by zsistla** [comment]
Part of #93

**Comment by zsistla** [comment]
Also, ensure `task` explanatory texts are `label`s not `echo`s.
For instance [this](https://github.com/newrelic/open-install-library/pull/359/files#diff-a34d073b4d6764ad6be1fd33e6ba607dda0e84ec50777ac5255c838b4904f5c9R145) should look more like what the [docs](https://github.com/newrelic/open-install-library/tree/main/docs#consistency) specify.

**Comment by joshuabenuck** [comment]
Implemented by open-install-library PRs [394](https://github.com/newrelic/open-install-library/pull/394), [399](https://github.com/newrelic/open-install-library/pull/399), and [400](https://github.com/newrelic/open-install-library/pull/400).
