### ISSUE TITLE
Missing newrelic_notice_error documentation

### ISSUE THREAD

**Issue by neclimdul** [newrelic/newrelic-php-agent#171]
## Description

One of the method signatures for newrelic_notice_error is ($errstr, $exception) but the documentation is missing the exception parameters
 
https://github.com/newrelic/newrelic-php-agent/blob/3f93ee47f80703d46d8fccd53be7d6b80361a594/agent/php_api.c#L63
https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_notice_error/

There doesn't seem to be any deprecation of this signature so not sure the expected behavior.

**Comment by cgvalayev** [comment]
Thank you, this was driving me nuts because of this mismatch:
https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/NewRelicHandler.php
https://docs.newrelic.com/docs/agents/php-agent/php-agent-api/newrelic_notice_error/

**Comment by zsistla** [comment]
Hi @neclimdul, 
Thanks so much for noticing the inconsistency and bringing it to our attention.
We've internally updated the documentation with the missing (but entirely valid) signature, and it should be updated on our main docs site in the next day or two.
Thanks for helping us make it more useful to future API users :)
