### ISSUE TITLE
Amazon Linux 2 (ARM) - Build from source failure

### ISSUE THREAD

**Issue by ifnull** [newrelic/newrelic-php-agent#173]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Running the `make` command fails on ARM based EC2 running Amazon Linux 2.

```
| 		     Syntax error
configure:5936: /lib/cpp  conftest.cpp
cpp: error trying to exec 'cc1plus': execvp: No such file or directory
configure:5936: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Protocol Buffers"
| #define PACKAGE_TARNAME "protobuf"
| #define PACKAGE_VERSION "3.13.0"
| #define PACKAGE_STRING "Protocol Buffers 3.13.0"
| #define PACKAGE_BUGREPORT "protobuf@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "protobuf"
| #define VERSION "3.13.0"
| /* end confdefs.h.  */
| #ifdef __STDC__
| # include <limits.h>
| #else
| # include <assert.h>
| #endif
| 		     Syntax error
configure:5966: error: in `/srv/specsonline.com/newrelic-php-agent/vendor/protobuf':
configure:5968: error: C++ preprocessor "/lib/cpp" fails sanity check
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

```
sudo yum update -y
sudo amazon-linux-extras install nginx1 php7.4 -y
sudo yum install -y less git curl which tar awscli amazon-efs-utils jq
sudo yum install -y --skip-broken php-intl php-curl php-dom php-exif php-fileinfo \
     php-hash php-json php-mbstring php-mysqli php-libsodium php-openssl \
     php-pcre php-imagick php-xml php-zip php-filter php-gd php-iconv \
     php-mcrypt php-simplexml php-xmlreader php-zlib

# NewRelic Specific
sudo yum install -y make glibc-devel gcc gcc-c++ patch golang php-devel bzip2 libcurl \
	libedit libjpeg libmcrypt libpng readline-devel libtidy libtool libxml2 libxslt \
	openssl pcre zlib 

git clone git@github.com:newrelic/newrelic-php-agent.git
cd newrelic-php-agent
make
```

## Expected Behavior

`make` command completes successfully and 

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* PHP 7.4
* AWS EC2 m6g.large /  amzn2-ami-hvm-2.0.20210427.0-arm64-gp2

**Comment by ifnull** [comment]
Looks like `gcc-c++` is also required for building from source. I was able to continue with the build process by running the following.

```sudo yum install -y pcre-devel gcc-c++```

**Comment by ifnull** [comment]
If anyone else gets stuck, this is basically what I did to get it working for Amazon Linux 2 on an ARM EC2 instance. Everything appears to be reporting as expected and I didn't get any build errors in the end. The `newrelic.so` file appears to have been automatically placed `/usr/lib64/php/modules` by the `make agent-install` command. If it is not there, you may need to `cp`
from `agent/modules/` or consult the [development docs](https://github.com/newrelic/newrelic-php-agent/blob/main/docs/development.md).

```sudo yum update -y
sudo amazon-linux-extras install nginx1 php7.4 -y
sudo chkconfig nginx on
sudo chkconfig php-fpm on

sudo yum install -y --skip-broken php-intl php-curl php-dom php-exif php-fileinfo \
     php-hash php-json php-mbstring php-mysqli php-libsodium php-openssl \
     php-pcre php-imagick php-xml php-zip php-filter php-gd php-iconv \
     php-mcrypt php-simplexml php-xmlreader php-zlib

sudo yum install -y make glibc-devel gcc gcc-c++ patch golang php-devel bzip2 libcurl \
     libedit libjpeg libmcrypt libpng readline-devel libtidy libtool libxml2 libxslt \
     openssl pcre zlib pcre-devel

git clone git@github.com:newrelic/newrelic-php-agent.git
cd newrelic-php-agent
make

sudo cp bin/daemon /usr/bin/newrelic-daemon
sudo mkdir /var/log/newrelic/

sudo bash -c 'cat <<EOF >>/etc/php.d/20-newrelic.ini
extension = "newrelic.so"

[newrelic]
newrelic.license = "REPLACE_WITH_REAL_KEY"
newrelic.logfile = "/var/log/newrelic/php_agent.log"
newrelic.appname = "PHP Application"
newrelic.daemon.logfile = "/var/log/newrelic/newrelic-daemon.log"
EOF'

sudo make agent-install
sudo systemctl start nginx
sudo systemctl start php-fpm
```

**Comment by zsistla** [comment]
@ifnull Thanks so much for including your steps!!

**Comment by avramovic** [comment]
@ifnull Thanks, this helped me a lot in making a deploy script (config file) for Elastic Beanstalk on Amazon AMI Linux 2 (ARM). The script can be found here: https://gist.github.com/avramovic/14df79f170caf69261faa671413337c6

Tested on PHP 8.0 with Apache server and it works. It takes a bit to compile, but it'll do it only the first time, every subsequent deploy it'll detect New Relic daemon and will skip installation. Make sure you set your New Relic license key and app name on lines 17 and 19. It also uses v9.21 of the agent, but that can be adjusted easily.

Btw, here's the [newrelic.so](https://github.com/newrelic/newrelic-php-agent/files/8716756/newrelic.so.zip) file that is produced with this method. Not sure if dropping it and the ini file would work, but someone might wanna try.
