### ISSUE TITLE
Epic: PHP 8.1 Agent Support

### ISSUE THREAD

**Issue by ruudk** [newrelic/newrelic-php-agent#177]
## Summary

PHP 8.1 will be released on 25 November 2021.

## Desired Behavior

Prepare the extension so that people can upgrade immediately when 8.1 is released. 

[PHP 8.1 Alpha 3](https://www.php.net/archive/2021.php#2021-07-08-1) was released a week ago and they plan to release Beta 1 on 22 July 2021.

## Possible Solution

* Setup CI to include PHP 8.1 beta channel
* Remove restriction that prevents installation on 8.1 (if there is any)

## Additional context

https://stitcher.io/blog/new-in-php-81

**Comment by ruudk** [comment]
PHP 7.1 Beta 1 was just [tagged](https://github.com/php/php-src/releases/tag/php-8.1.0beta1).

**Comment by ruudk** [comment]
PHP Beta 2 was just released https://news-web.php.net/php.general/327595

@Fahmy-Mohammed any update from NewRelic on the plan? Can we start updating CI? I really don't want another PHP 8.0 scenario.

**Comment by ruudk** [comment]
PHP beta 3 released

https://twitter.com/official_php/status/1428409949521158146?s=12

when is NewRelic going to reply here ?

**Comment by ruudk** [comment]
RC 3 was just released. https://twitter.com/allaertpatrick/status/1443629312209530886?s=21

**Comment by ruudk** [comment]
RC 6 released https://twitter.com/allaertpatrick/status/1458847242970882048?s=12

2 more weeks for 8.1 final 🥳

**Comment by ruudk** [comment]
@ak-war @mfulb @zsistla PHP 8.1 was released on Thursday 25th of November. I see lots of activity lately on this repository regarding PHP 8.1 which is great 🙌 . 

I'm wondering if there is already an ETA available. Are we talking about days, weeks or months?

**Comment by icanhazstring** [comment]
Is there anything we can support you with?

**Comment by pascaldevink** [comment]
Happy new year! How is the support for PHP 8.1 coming along? Any updates or timelines we can use for planning an upgrade?

**Comment by icanhazstring** [comment]
As far as my Infos are going:

PHP 8.1 releases are split into 3 phases:
 
1. First phase is to support PHP 8.1 and ZTS (Zend) framework for PHP 8.0 and PHP 8.1 - this is targeted for mid-February 2022 release. 
2. The second phase is Fibers support 
3. The third is JIT support (which there is still very little request for by other customers)
 
Phase 2 and 3 do not have finalised timeframes yet.

**Comment by Ak-x** [comment]
This portion of the 8.1 Epic is complete.  The remainder of the 8.1 Epic will be completed through the Php 8.1 Agent Deployment - https://github.com/newrelic/newrelic-php-agent/issues/327

**Comment by ruudk** [comment]
What does it mean? Does it mean we can install the extension with PHP 8.1?

I find all these issues and epics without context extremely confusing.

**Comment by icanhazstring** [comment]
> What does it mean? Does it mean we can install the extension with PHP 8.1?
> 
> I find all these issues and epics without context extremely confusing. 

Everything related to support PHP 8.1 is ready. I would recon that means deployment is missing. E.g. creating the packages for certain Unix distros and stuff.

**Comment by rvanlaak** [comment]
Would it be an idea to reopen this issue until 8.1 support actually is available? Or does https://github.com/newrelic/newrelic-php-agent/issues/327 replace this issue?

**Comment by mfulb** [comment]
We have transitioned to #327 for tracking the deployment of the next agent release.
