### ISSUE TITLE
PHP: Virtuoso: documentation needed for exit status 7

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#202]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg:
rhel
default,assert_pre_req
execution failed for php-agent-installer: exit status 7

This error indicates that the recipe did not run as sudo and needs to be documented in the troubleshooting guide.

Part of #200

**Comment by ZNeumann** [comment]
https://github.com/newrelic/open-install-library/pull/496

**Comment by mfulb** [comment]
The preInstall now checks if the recipe is run as sudo so the error should not occur any more.
I don't think we need to document this as a result of this.
