### ISSUE TITLE
PHP: Virtuoso: Set up development environment

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#203]
Spin up a PHP Virtuoso development environment to investigate issues.  Refer to the [MMF](https://docs.google.com/document/d/1JEJ16u6G2Q-Od7hdtDcHXpyJjHLiRaciSSp8-9RjeqY/edit#) (_New Relic Internal Only_) document for details.

**Comment by mfulb** [comment]
I believe this has been completed.
