### ISSUE TITLE
PHP: Virtuoso: documentation needed for exit status 20

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#204]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg:
Rhel, deb
default,assert_pre_req
execution failed for php-agent-installer: exit status 20

This error indicates that the recipe did not detect systemd which is a requirement and needs to be documented in the troubleshooting guide.

Part of #200.

**Comment by ZNeumann** [comment]
https://github.com/newrelic/open-install-library/pull/496

**Comment by mfulb** [comment]
The preInstall will check for this and the error should not occur now.  Instead a log message will be generated in the newrelic-cli.log file explaining that system is required for installing the PHP agent.
