### ISSUE TITLE
PHP: Virtuoso: php-agent-installer fork fails - permission denied

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#208]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg: 
rhel
default,install_tarball
execution failed for php-agent-installer: fork/exec /tmp/WHATEVERTEMPDIR/newrelic-php5-9.17.1.301-linux/newrelic-install: permission denied

Part of #200

**Comment by mfulb** [comment]
Doing a search back 21 days shows almost all of these (62 of 66 records) are on Centos, 56 on Centos 7.9.2009 and 6 on Centos 8.4.2105.  The remainder were RHEL 8.4 and 7.9.

**Comment by mfulb** [comment]
I wonder if this has to do with SELinux on these systems - perhaps the system is configured to not allow files in /tmp to execute for example?  I have found on AWS instances I have deployed with Centos 7.9.2009 this is not the case but I wonder if in some cases users have added to the default permissions resulting in this error.

**Comment by mfulb** [comment]
We've seen 1 failure like this now on a ubuntu 20.04 system which seems to indicate it goes beyond SELinux.

**Comment by ZNeumann** [comment]
Could be a bug involving /tmp/ mounted as a separate partition with noexec option. Something to look into...

**Comment by mfulb** [comment]
That is a good suggestion - I'll get a test deploy setup and test this.

**Comment by mfulb** [comment]
The open-install-library PR [507](https://github.com/newrelic/open-install-library/pull/507) contains a check for if /tmp is mounted "noexec" and should address this issue.
