### ISSUE TITLE
PHP: Virtuoso: Failed to restart SYSTEMSPECIFICFPMSERVICE - not found

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#209]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg:
debian
default,restart_services
execution failed for php-agent-installer: exit status 5: Failed to restart SYSTEMSPECIFICFPMSERVICE: Unit SYSTEMSPECIFICFPMSERVICE not found.

Part of #200

**Comment by zsistla** [comment]
`SYSTEMSPECIFICFPMSERVICE` variations seen in last few weeks:

execution failed for php-agent-installer: exit status 5: Failed to restart php-fpm.service: Unit not found.

execution failed for php-agent-installer: exit status 5: Failed to restart php-fpm.service: Unit php-fpm.service not found.

execution failed for php-agent-installer: exit status 5: Failed to restart php7.3-fpm.service: Unit not found.

execution failed for php-agent-installer: exit status 5: Failed to restart php7.4-fpm.service: Unit php7.4-fpm.service not found.

**Comment by ZNeumann** [comment]
https://github.com/newrelic/open-install-library/pull/510
