### ISSUE TITLE
PHP: Virtuoso: exit status 1 - redirecting to /bin/systemctl/restart php-fpm.service

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#211]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg:
rhel
default,send_transaction
execution failed for php-agent-installer: exit status 1: Redirecting to /bin/systemctl restart php-fpm.service

Part of #200

**Comment by mfulb** [comment]
This seems related to #209 - in this case the message output is generated because the redhat recipe for installing the php agent uses 'service' to restart the php-fpm process.  Since RHEL uses systemd any calls to 'service' are redirected to the equivalent call to systemctl.   I don't think this message is the actual error as it is expected.  Like the other #209 style issues there is something else wrong here - perhaps there was no php-fpm.service file for example.   

I have not been able to reproduce this issue using a stock linux2 ami image on aws. 
 Needs further investigation - I wonder if these are happening because a different php package than the default one from Red Hat was installed so the service files are named differently.

**Comment by mfulb** [comment]
Also the issue is reported to have occurred  in the "send_transaction" task which does not contain any calls to restart a service so the issue message about systemctl most likely did not occur during the "send_transaction" task.

**Comment by zsistla** [comment]
I wonder if it would be helpful to try to catch any errors [here](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/php/debian.yml#L413) and then proceed accordingly.

**Comment by mfulb** [comment]
I believe this is happening when PHP is not installed.  The actual error occurs in the "send_transactions" task when PHP is run with "--ini" with stderr redirected to /dev/null.  When this fails (since PHP is not installed) sudo generates an exit code of 1 and the installer sees the last output "redirecting to /bin/systemctl/restart php-fpm.service" (which is just a informational message from the "service" command saying it is going to use systemctl to restart the service) and treats that as the error message.

This is probably the source of many of these errors.

Now we are checking for PHP being installed before attempting the installation this should not happen any longer.
