### ISSUE TITLE
PHP: Virtuoso: exit status 1: newrelic.list: No such file or directory

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#213]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg:
debian
default,install_deb
execution failed for php-agent-installer: exit status 1: tee: /etc/apt/sources.list.d/newrelic.list: No such file or directory

Part of #200

**Comment by ZNeumann** [comment]
https://github.com/newrelic/open-install-library/pull/503

**Comment by mfulb** [comment]
The open-install-library PR [507](https://github.com/newrelic/open-install-library/pull/507) contains a check in the preInstall and install task "assert_pre_reqs" to make sure the directory /etc/apt/sources.list.d exists and sure eliminate this issue.
