### ISSUE TITLE
PHP: Virtuoso: sed improper usage

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#215]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg:
debian
default,configure
execution failed for php-agent-installer: exit status 1: sed: -e expression #1, char 64: unknown option to `s'

Part of #200

**Comment by ZNeumann** [comment]
This is triggered when a user chooses an application name with '/' because of sed formatting

**Comment by ZNeumann** [comment]
https://github.com/newrelic/open-install-library/pull/506
