### ISSUE TITLE
PHP: Virtuoso: exit status 5: Failed to restart php-fpm.service

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#221]
The PHP Virtuoso dashboard shows the following error:

OS, Task, and Error msg:
debian/rhel 
default,restart_services
execution failed for php-agent-installer: exit status 5: Failed to restart php-fpm.service: Unit php-fpm.service not found.

Part of #200

**Comment by zsistla** [comment]
I think this is a duplicate of #209

**Comment by mfulb** [comment]
Closed as it is covered by #209 already.
