### ISSUE TITLE
PHP Warning:  JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0

### ISSUE THREAD

**Issue by vedmant** [newrelic/newrelic-php-agent#223]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When I enable JIT and newrelic extensions I get this:

```
PHP Warning:  JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0
```

The warning disappears when I disable newrelic extension

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Install php 8
Enable JIT
Install newrelic
try `php -v`

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

No warning

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

CentOS Linux release 7.9.2009 (Core)

Installed Packages

Name        : newrelic-php5
Version     : 9.18.1.303
Release     : 1
From repo   : newrelic

Name        : php
Arch        : x86_64
Version     : 8.0.10
Release     : 2.el7.remi
Size        : 5.1 M

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by zsistla** [comment]
Hi @vedmant , thanks for bringing this to our attention.  Unfortunately, this is a known issue that PHP 8 introduced in 8.0.1.

We have an [issue already dedicated](https://github.com/newrelic/newrelic-php-agent/issues/50) to this and are tracking it in our roadmap.  We'll include all updates in #50.

Please refer to #50 to track updates and progress, and I'll close this as a duplicate.
