### ISSUE TITLE
PHP: Virtuoso: Error "killall": executable file not found in $PATH on Centos 7.9

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#225]
When using the redhat.yml recipe to install the PHP agent on a Centos 7.9 system the error:

"killall": executable file not found in $PATH

occurs in the "clean_slate" task.  This is because killall is not instlled by default on a Centos 7.9 system.

It can be installed using the psmisc package.

Or alternately the pkill utility has been suggested as a more portable tool for killing a process that is installed by default on Centos 7.9.

The install process continued after this error.  The result was that the newrelic-daemon was not terminated as intended due to the command failing.

**Comment by zsistla** [comment]
As an alternative, could we also consider doing `service newrelic-daemon stop`  here?

**Comment by mfulb** [comment]
That seems like it would be a good approach.

**Comment by mfulb** [comment]
The newrelic-daemon service script does not appear to work properly on Centos 7.9 (#231) which would need to be investigated before trying the solution using the service command to stop the daemon.
