### ISSUE TITLE
PHP: Virtuoso: Create a PreInstall block in recipes to check for dependencies BEFORE installation.

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#227]
Virtuoso is now shifting the direction to handle all the unsupported cases (i.e., cases where the system doesn't have the right dependencies) through the NR1 UI, leading the user to our documentation which supports all the various scenarios.
The Guided install would only be used for what we can automate with high confidence. 

Tracking a dependency-related failure exit code, is more of an unsupported case here, and ideally we should identify this in the preInstall script before the recipe even gets to the install point.
For the preInstall, the execution result is binary, it's either good to execute the recipe (0 exit code), or not ok to execute the recipe (non 0 exit code).
Here is an extensive example for [java](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/apm/java/linux.yml#L21-L45).

This looks like a way for us to reduce the dependency related "errors". 

For this ticket we need to add the `preInstall: requireAtDiscovery` block to detect dependencies BEFORE the install is initiated.  The prereq task block is fine to leave as a fail-safe.

**Comment by mfulb** [comment]
The open-install-library PR [507](https://github.com/newrelic/open-install-library/pull/507) contains this work.
