### ISSUE TITLE
Support for ZTS

### ISSUE THREAD

**Issue by raupie** [newrelic/newrelic-php-agent#233]
```
This will be the last release in which ZTS builds are supported. In the future, ZTS builds may not be provided, and support may be completely pulled from the codebase.
```

For v9.17.0, this is the last version that supports ZTS builds. 

What are the full implications of this change? If I'm using a php image with ZTS enabled, will the agent not work at all or will it only be unable to profile applications using pthreads? Sorry I don't fully understand.

**Comment by Ak-x** [comment]
Hello @raupie, [Support for ZTS builds ended with release v9.19.0.309.](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-5-0-317/)

**Comment by rvanlaak** [comment]
@Ak-x why did ZTS support end? You share a link with the exact same sentence, while it's expected that rationales get shared on this decision. It blocks the agent from being installed with Frankenphp (all big framework's preferred application server).
