### ISSUE TITLE
PHP: Virtuoso: Handle application name more robustly

### ISSUE THREAD

**Issue by ZNeumann** [newrelic/newrelic-php-agent#250]
Current application name input goes through Go, causing the name to be added to the recipe wherever the variable is referenced. This allows bash injection. The fix is to change the way that application-name is input to avoid this.

OS, Task, and Error msg:
rhel, debian
default,configure
exit status 127: INJECTION_HERE: executable file not found in $PATH”

**Comment by Ak-x** [comment]
Related to: https://github.com/newrelic/open-install-library/pull/889
