### ISSUE TITLE
[PHP] PHP 8.1 Support Exploration

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#258]
Description
PHP8.1 is coming in November 2021. The main change is support for fibers (coroutines). Use of fibers by a PHP application will most certainly impact the behavior of the agent.

This MMF is to continue the initial time-boxed effort for the team to explore PHP 8.1 and create a plan for next steps in adding PHP 8.1 support.

Acceptance Criteria

- [x] identified PHP 8.1 changes impacting the current features of the PHP agent
- [x] identified PHP 8.1 changes that could provide us new PHP agent feature opportunities
- [x] created a rough plan for implementing support for PHP 8.1
- [x] scoped the plan
- [x] added MMFs and acceptance criteria for additional required MMFs

**Comment by gael-donat** [comment]
Hi,

Do you have any ETA for supporting php 8.1 ? moving from PHP7 to PHP8 took severals months and I would love to have PHP 8.1 support before june :D

Thanks !

**Comment by shaneniebergall** [comment]
> Hi,
> 
> Do you have any ETA for supporting php 8.1 ?
> 
> Thanks !

According to [here](https://github.com/newrelic/newrelic-php-agent/milestone/11), looks like it's scheduled for Jan 31 2022

**Comment by lptn** [comment]
>According to here, looks like it's scheduled for Jan 31 2022

OMG, that's an unpleasant surprise. Newrelic again shipping PHP agent too late, everything is ready from ecosystem, only newrelic so slow :(

**Comment by icanhazstring** [comment]
Not true. Some tooling just recently added 8.1 support, some still working on it with a plan of adding support by the end of month.

So give them some slack, it's end of the year, nothing much happening either way. So no point in given them bad credits or pressure for having it at the end on January.

**Comment by lptn** [comment]
@icanhazstring 

Well, I'm working on projects that use Laravel, Symfony, Psalm, PHPStan, Rector, PHPCS, PHP-CS-Fixer, few composer plugins and other tools, all of them were ready for the new PHP version, this is why I wrote "the ecosystem is ready". The only one roadblocker, 2nd time in a row, newrelic agent (but previous release was major, I can understand some delay). PHP had few beta and RC releases (PHP **[8.1.0RC1](https://github.com/php/php-src/releases/tag/php-8.0.10RC1)** was tagged 10 Aug 2021 - 4 months ago).

From PHP Agent docs:

>New Relic recommends that you upgrade the agent regularly and at a minimum every 3 months.

the latest Agent version, PHP agent v9.18.1.303 was released August 23, 2021. Let's compare with Agent releases for a new minor Python version:

Python 3.10 released at October 04, 2021, at October 12, 2021 [Python agent v7.2.0.167](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70200167/) were released (with Python 3.10 support).

I of course don't know enough information, but from the regular user standpoint, it seems like NewRelic doesn't pay enough attention PHP agent (the delay for PHP 8.0 version was almost 5 (!!!) months: 26 Nov 2020 - 21 Apr 2021).

As for your points about the end of the year: business don't speak these terms. For business, end of year is 1-3 extra holidays and some accounting, it should not block releases.

**Comment by ruudk** [comment]
@lptn Don't bother, it doesn't help 🙁

I created [this issue](https://github.com/newrelic/newrelic-php-agent/issues/177) already in June and yet here we are again,

**Comment by icanhazstring** [comment]
> @icanhazstring 
> 
> Well, I'm working on projects that use Laravel, Symfony, Psalm, PHPStan, Rector, PHPCS, PHP-CS-Fixer, few composer plugins and other tools, all of them were ready for the new PHP version, this is why I wrote "the ecosystem is ready". The only one roadblocker, 2nd time in a row, newrelic agent (but previous release was major, I can understand some delay). PHP had few beta and RC releases (PHP **[8.1.0RC1](https://github.com/php/php-src/releases/tag/php-8.0.10RC1)** was tagged 10 Aug 2021 - 4 months ago).
> 
> From PHP Agent docs:
> 
> >New Relic recommends that you upgrade the agent regularly and at a minimum every 3 months.
> 
> It sounds ironic. The latest Agent version, PHP agent v9.18.1.303 was released August 23, 2021. Let's compare with Agent releases for a new minor Python version:
> 
> Python 3.10 released at October 04, 2021, at October 12, 2021 [Python agent v7.2.0.167](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-70200167/) were released (with Python 3.10 support).
> 
> I of course don't know enough information, but from the regular user standpoint, it seems like NewRelic doesn't pay enough attention PHP agent (the delay for PHP 8.0 version was almost 5 (!!!) months: 26 Nov 2020 - 21 Apr 2021).
> 
> As for your points about the end of the year: business don't speak these terms. For business, end of year is 1-3 extra holidays and some accounting, it should not block releases.
> 

Just to recap:
- You rely on open source
- You adopt early despite knowing that some dependencies you know taking some time longer to migrate
- You just complain without helping much
- You say all your tools are Php8.1 ready? No they are not

https://phpstan.org/r/113a770b-7e79-4bf7-866f-07c9a35e1b21

If you say business doesn't work this way, you still have a lot to learn.

**Comment by zsistla** [comment]
Hi all,

Thanks so much for your interest and engagement surrounding PHP 8.1 support in the PHP Agent.
This is our current priority project, and our team is excited to be working on getting PHP 8.1 support out as soon as possible.  This is a [multipart project](https://github.com/newrelic/newrelic-php-agent/milestone/11) for us which include upgrading the agent, upgrading tests to exercise new PHP 8.1 features and provide a quality product, and updating release/build/test infrastructure.
We're currently upgrading the agent and hope to continue to work through the tickets quickly to get this released.

**Comment by elnur** [comment]
I'm unhappy, too. Second time in a row. Why can't you guys start working on new PHP version support before it becomes production ready? You're the only ones keeping us from upgrading to 8.1. Everything else is ready.

Don't you consider your customers using PHP as high value ones? Will your bottom line not budge significantly if PHP users start switching to alternatives? Is that your message to your PHP customers?

**Comment by gempir** [comment]
Is it possible to compile the old version to be at least compatible with 8.1 without supporting any new Features?

**Comment by zsistla** [comment]
Hello,

@elnur , we can certainly understand the frustration of waiting for a tool to update in order to upgrade an overall solution.  This is the current priority of our team, and we are working to finish it as soon as possible.

@gempir , thanks for brainstorming solutions to speed up the process; however, compiling with 8.1 is only part of what we need to do.  We have been working in our [dev branch](https://github.com/newrelic/newrelic-php-agent/tree/dev) to get the 8.1 compatibility. However, we take quality seriously and to ensure any changes don't affect the performance, functionality, or stability of our agent across all the many PHP versions (PHP 5.5+) and OSs and many OS versions that we support, we have a wide build and test infrastructure that needs to incorporate PHP 8.1 as well as an extensive suite of tests that also need to be updated and all successfully run before we officially release.  This is our team's absolute top priority right now, and we are working to get all the pieces finished.

**Comment by ak-war** [comment]
@gael-donat  thank you for reaching out. We have an initial PHP 8.1 release coming out in February (next month). Will update further as we near the release date.

**Comment by elnur** [comment]
Hey, New Relic, just wanted to use this great opportunity to thank you all again for being the only fucking reason we have to stay on 8.0 for 3 more months. You're doing such a wonderful fucking job.

**Comment by icanhazstring** [comment]
> Hey, New Relic, just wanted to use this great opportunity to thank you all again for being the only fucking reason we have to stay on 8.0 for 3 more months. You're doing such a wonderful fucking job.

Oh no. 😂

**Comment by deefour** [comment]
@Ak-x @mfulb can we get an update on timing for 8.1 support or can you point us to where such an update has been posted?

It seems there are a lot of us seeking communication. We need to make decisions around new feature work - whether or not we can rely on New Relic for 8.1 support soon.

**Comment by lptn** [comment]
When I read this issue, I feel like I'm in a Hollywood movie 🍿 .

PS: The community is really waiting for an update. I'll appreciate at least a public beta, at least without Fiber support (if this is a roadblock)

@ak-war 
>We have an initial PHP 8.1 release coming out in February (next month). Will update further as we near the release date.

tick tock 🕥

**Comment by ak-war** [comment]
Thank you everyone for your valuable feedback and comments. As always we appreciate your constructive inputs and I would like to assure you that our team is completely focused on delivering PHP 8.1 support as soon as we can. As our team works through the last few open items with a strong focus on agent quality and performance, we are planning on providing more specifics by the end of this week regarding the release date.

**Comment by decocodes** [comment]
We did postponed the upgrade of our main app the maximum time we could.

Sadly we will have to lookup for another option for a while.

**Comment by ak-war** [comment]
We would like to assure you that our team is working hard on the PHP 8.1 support items and this is our top priority. We are looking to release PHP 8.1 support by 9th March 2022.

**Comment by ruudk** [comment]
Would it be possible to just ship a beta already? Or if everything that is ready is merged to dev, that we can just compile the PHP 8.1 extension from source? I'm tired of waiting any longer, it's been 227 days since I raised this issue:
- https://github.com/newrelic/newrelic-php-agent/issues/177

**Comment by ak-war** [comment]
Thank you everyone, for your patience and feedback. PHP 8.1 support has been released: https://github.com/newrelic/newrelic-php-agent/releases

**Comment by TheFrankman** [comment]
@ak-war - What assurances do we have that support for the next PHP release will be done in a more timely manner. I'm sure I am not alone in questioning if we can continue to use New Relic, a service we pay a great deal of money for, if we can go nearly 200 days without an update.

**Comment by ruudk** [comment]
@TheFrankman Created a new issue for PHP 8.2: 
- https://github.com/newrelic/newrelic-php-agent/issues/375
