### ISSUE TITLE
[PHP] Explore PHP 8.1 fibers (coroutines) implications

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#259]
The goal is to explore the implications of the addition of fibers to PHP 8.1 and determine  any needed implementation tasks (ideally with scope and time estimates).

Find and explore areas of breakage enough to get an idea of the scope and then document the effort in the implementation MMF/issue tickets.

Part of #258

Acceptance Tasks:
- [ ] Investigate PHP 8.1 RC5 and record findings
- [ ] Investigate PHP 8.1 FINAL RELEASE and record findings

**Comment by zsistla** [comment]
Findings [documented](https://docs.google.com/document/d/17UidG_20W-CAWAU-wTS1zq3uJoG5Jkm1pDnaweGCcKM/edit#heading=h.bsbv6dtbs2s2) and [scoped](https://docs.google.com/document/d/11-mGe3sYTe252sZUd_zrV4tf8b9_PiPlDEJHbcDaoLY/edit#bookmark=id.s5sd10k47win).
