### ISSUE TITLE
[PHP] Explore PHP 8.1 Internal API signature and behavioral changes.

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#260]
The goal is to explore the implications of  any  Internal API signature and behavioral changes with PHP 8.1 and determine any needed implementation tasks (ideally with scope and time estimates).

Find and explore areas of breakage enough to get an idea of the scope and then document the effort in the implementation MMF/issue tickets.

Changes are documented here: [UPGRADING.INTERNALS](https://github.com/php/php-src/blob/PHP-8.1/UPGRADING.INTERNALS#L24).

Part of #258.

Acceptance Tasks:
- [x] Investigate PHP 8.1 RC6 and record findings
- [ ] Investigate PHP 8.1 FINAL RELEASE and record findings

**Comment by mfulb** [comment]
The following APIs have been removed from the Zend Engine:

- The spl_ce_Aggregate, spl_ce_ArrayAccess, spl_ce_Countable, spl_ce_Iterator, spl_ce_Serializable, spl_ce_Stringable, spl_ce_Traversable alias class entries have been removed in favor of zend_ce_aggregate, zend_ce_arrayaccess, zend_ce_countable, zend_ce_iterator, zend_ce_serializable, zend_ce_stringable,  zend_ce_traversable.
  - Agent Implications
    - The agent does not use any of these APIs.
- The ZVAL_NEW_ARR() macro has been removed. Use array_init() or ZVAL_ARR  with zend_new_array() instead.
  - Agent Implications
    - The agent does not appear to use this macro.
- The IGNORE_URL_WIN macro has been removed; it had no effect as of PHP 5.0.0.
  - Agent Implications
    - The agent does not appear to use this macro.
- TsHashTable has been removed, it was not used in php-src and was not useful outside of php-src.
   - Agent Implications
     - The agent does not appear to use this macro.

**Comment by mfulb** [comment]
Zend Stream API has been changed to use "zend_string*" instead of "char*"
- zend_file_handle.filename now is zend_string*
- zend_file_handle.free_filename is removed. Now zend_file_handle.filename is always released.
- added zend_file_handle.primary_script flag. SAPIs should set it for main executed script.
- added zend_file_handle.in_list flag, which is set when a file_handle is added into CG(open_files)
- added zend_stream_init_filename_ex() function, that takes filename as zend_string*
   the "filename" parameter of functions zend_stream_open(), php_stream_open_for_zend_ex() and callback 
   zend_stream_open_function() has been removed (it's now passed as a "filename" field of the file_handle 
   parameter)
- in zend_fopen() and zend_resolve_path() callbacks filename now passed as zend_string*
  file_handles should be destroyed by zend_destroy_file_handle() function (usually in the same function where 
   they were created by zend_stream_init_*()). Previously there were two different destructors 
   zend_destroy_file_handle() and zend_file_handle_dtor().
- zend_ini_scanner_globals.filename now is zend_string*

Agent Implications
    - zend_file_handle is referenced in the typedef for ntphjpcfile_t in php_newrelic.h but doesn’t seem to be used anywhere in the code base - legacy reference that wasn’t cleaned up?
    - The rest of the changes do not appear to affect the agent code.

**Comment by mfulb** [comment]
- Added the zend_get_opcode_id() function, which is intended to get opcode id from name.
**Agent Implications**
  - Does not appear to affect current behavior as it is an added functionality.
- Removed support for "p" modifier (%pd, %pu, etc) in PHP's printf     implementations. Use ZEND_LONG_FMT and ZEND_ULONG_FMT instead.
**Agent Implications**
   - Unclear how this affects the agent - would need further investigation.
- ZEND_ATOL() now returns the integer instead of assigning it as part of the macro. Replace ZEND_ATOL(i, s) with i = ZEND_ATOL(s).
**Agent Implications**
  - Does not appear to be used in agent.
- Non-serializable classes should be indicated using the    ZEND_ACC_NOT_SERIALIZABLE (@not-serializable in stubs) rather than the     zend_class_(un)serialize_deny handlers which are removed.
**Agent Implications**
   - Does not appear to be used in agent.
- _zend_hash_find_known_hash has been renamed to zend_hash_find_known_hash.
**Agent Implications**
  - Does not appear to be used in agent.
- ZEND_TYPE_HAS_CLASS() has been renamed to ZEND_TYPE_IS_COMPLEX() for clarity. A zend_type element can contain a zend_type_list which might be either a union or an intersection, or a single class stored as either a zend_string* or a zend_class_entry*.
**Agent Implications**
  - Does not appear to be used in agent.
- The handle member of zend_resource (the resource ID) now has type zend_long     rather than int. This should be transparent to most code, but uses in printf may need to switch from "%d" to ZEND_LONG_FMT.
**Agent Implications**
   - Does not appear to be used in agent.

**Comment by zsistla** [comment]
Looks like a great job to explore further in the implementation MMF!
