### ISSUE TITLE
[PHP] Update PHP 8.1 prototype to each PHP 8.1 RC 

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#261]
PHP 8.1 RC5 was released 10/28/21.  The current prototype for the agent under PHP 8.1 was last updated for RC4.  The purpose of this task is to update the prototype to build against RC5 and run tests against the updated prototype and report findings.

Part of #258.

Acceptance Tasks:
- [X] Update prototype to PHP 8.1 RC5 (released 10/28/21)
- [x] Update prototype to PHP 8.1 RC6 (released 11/11/21)

**Comment by crishoj** [comment]
Any estimate for PHP 8.1 support in the agent?

**Comment by mfulb** [comment]
Moving checking compile prototype for PHP 8.1 to a separate tracking issue.

**Comment by ak-war** [comment]
@crishoj thank you for reaching out. We have an initial PHP 8.1 release coming out in February (next month). Will update further as we near the release date.
