### ISSUE TITLE
[PHP] Explore PHP 8.1 New Functions

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#264]
The goal is to explore the implications of any new function changes with PHP 8.1 and determine any needed implementation tasks (ideally with scope and time estimates).

Find and explore areas of potential benefit from leveraging new functions enough to get an idea of the scope and then document the effort in the implementation MMF/issue tickets.

Changes are documented here: [UPGRADING](https://github.com/php/php-src/blob/PHP-8.1/UPGRADING#L505).

Part of #258.

Acceptance Tasks:
- [x] Investigate PHP 8.1 RC6 and record findings
- [ ] Investigate PHP 8.1 FINAL RELEASE and record findings

**Comment by zsistla** [comment]
Checked RC6 - no changes impact the agent.
