### ISSUE TITLE
[PHP] Explore PHP 8.1 Deprecated Functionality

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#266]
The goal is to explore the implications of any deprecated functionality with PHP 8.1 and determine any needed implementation tasks (ideally with scope and time estimates).

Find and explore areas of change enough to get an idea of the scope of any work and then document the effort in the implementation MMF/issue tickets.

Changes are documented here: [UPGRADING](https://github.com/php/php-src/blob/PHP-8.1/UPGRADING#L347).

Part of #258.

Acceptance Tasks:
- [x] Investigate PHP 8.1 RC5 and record findings
- [x] Investigate PHP 8.1 RC6 and record findings

**Comment by ZNeumann** [comment]
Depreciation categories:

Core: Doesn't appear to affect the agent
CType: Doesn't appear to affect the agent
Date: Doesn't appear to affect the agent
Filter: Doesn't appear to affect the agent
GD: Doesn't appear to affect the agent
Hash: Doesn't appear to affect the agent
IMAP: Doesn't appear to affect the agent
Intl: Doesn't appear to affect the agent
Mbstring: Doesn't appear to affect the agent
MySQLi: Doesn't appear to affect the agent
OCI8: Doesn't appear to affect the agent
ODBC: Doesn't appear to affect the agent
PDO: Doesn't appear to affect the agent
SOAP: Doesn't appear to affect the agent
Standard: Doesn't appear to affect the agent

PgSQL:
Mix-and-matching of default/defined connection object to pgsql functions is deprecated. This feature is currently not in the agent, but is in the backlog. see [https://github.com/newrelic/newrelic-php-agent/issues/276](https://github.com/newrelic/newrelic-php-agent/issues/276)

**Comment by mfulb** [comment]
No changes to impact with RC6.
