### ISSUE TITLE
Unable to load dynamic library 'newrelic.so', PHP8.0.11

### ISSUE THREAD

**Issue by lazarenkoalexey** [newrelic/newrelic-php-agent#284]
Fixed in version 9.18 of the agent

_Originally posted by @Fahmy-Mohammed in https://github.com/newrelic/newrelic-php-agent/issues/172#issuecomment-900681479_

Hi!

Tried using newrelic.so module from new relic agent:
```
-rwxr-xr-x 1 root root 1739216 Aug 20 21:58 /usr/lib/newrelic-php5/agent/x64/newrelic-20200930.so
-rwxr-xr-x 1 root root 1739048 Aug 20 21:58 /usr/lib/newrelic-php5/agent/x64/newrelic-20200930-zts.so
```

PHP 8.0.11 (cli) (built: Oct  6 2021 08:43:42) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v4.0.11, Copyright (c) Zend Technologies

New Relic daemon version 9.18.1.303-8bc3f05acf05

Still have the error:
```
[11-Nov-2021 14:53:17 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'newrelic.so' (tried: /usr/lib64/php/modules/newrelic.so (/usr/lib64/php/modules/
newrelic.so: undefined symbol: compiler_globals), /usr/lib64/php/modules/newrelic.so.so (/usr/lib64/php/modules/newrelic.so.so: cannot open shared object file: No suc
h file or directory)) in Unknown on line 0
```

Thanks in advance!

**Comment by LiBrusmc** [comment]
Hi Team,
+1 to the mentioned above problem with a newrelic.so module.
Is there any workaround/solution on this matter? 
Thank you in advance for raising the issue!

**Comment by mfulb** [comment]
Part of #327.

**Comment by mfulb** [comment]
ZTS support has been confirmed as enabled for upcoming 9.19 release.
