### ISSUE TITLE
[PHP] Verify changes to agent to accommodate PHP 8.1 internal API changes

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#291]
Numerous changes were required in the PHP 8.1 compile prototype as a result of PHP 8.1 internal API changes.  This issue involves verifying these changes.

Acceptance Tasks:
- [x] zend_file_handle is referenced in the typedef for ntphjpcfile_t in php_newrelic.h but doesn’t seem to be used anywhere in the code base - legacy reference that wasn’t cleaned up?

**Comment by zsistla** [comment]
regarding zend_file_handle, it is part of an internal hook. See here for info: https://www.phpinternalsbook.com/php7/extensions_design/hooks.html#hooking-into-script-file-compilation
