### ISSUE TITLE
[PHP] Verify unit tests pass after merging compile prototype

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#292]
Verification is required that the unit tests (valgrind,etc) pass on the dev branch after the PHP 8.1 compile prototype is merged.

Acceptance Tasks:
- [x] Unit tests pass after compile prototype merged

**Comment by zsistla** [comment]
This is dependent on the [curl PR](https://github.com/newrelic/newrelic-php-agent/pull/318) being merged first.

**Comment by mfulb** [comment]
I have confirmed that "make valgrind" passes using the official PHP 8.1 source release and the dev branch with the PHP 8.1 support PR and the curl PR merged.
