### ISSUE TITLE
[PHP] Investigate change in PHP 8.1 mysqli default error handling mode

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#299]
The default error handling mode for mysqli in PHP 8.1 is now to raise an exception.  Verify this does not affect the agent code or mysqli integration tests which may have assumed the previous default of MYSQLI_REPORT_OFF.

Acceptance Tasks:
- [x] Verify change of default error handling of mysqli to raise an exception does not impact the agent or tests.

**Comment by ZNeumann** [comment]
I didn't find any potential impacts.
