### ISSUE TITLE
PHP8 MMF#1: Install agent in PHP8 w/o faults

### ISSUE THREAD

**Issue by elucus** [newrelic/newrelic-php-agent#30]
The outcome of this work is ability to use the PHP agent in an PHP 8 environment without crashes and to clearly document how to configure a PHP 8 service to be used with this base bones PHP8 support in our PHP agent.

This is part of multiple MMFs for PHP 8 work as outlined below.

MMF#1 [<ins>Agent with PHP 8 support </ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.hx9v342k5zzq)
--
MMF#2 [<ins>Build Environment with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy)
MMF#3 [<ins>Update Agent Tests with PHP 8.0 </ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.p2q7qbb5pbkr)
MMF#4 [<ins>Release Agent with PHP 8.0 Support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.et7wy5raaa9)

**Comment by jodeev** [comment]
Testing integration with Aha. Closing this issue - wrong creds.
