### ISSUE TITLE
Update nrcamp/nlcamp to build final release of PHP 8.1

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#307]
This ticket is for the task of updating the build scripts aside from php-build-scripts to include building the final release of PHP 8.1 - this includes nrcamp/nrlamp.

**Comment by zsistla** [comment]
Part of #327

**Comment by mfulb** [comment]
This work is complete and awaiting merge of PRs to NRLAMP and NRCAMP repos.

**Comment by mfulb** [comment]
Merged changes on NRLAMP/NRCAMP repos.
