### ISSUE TITLE
[PHP] Update FreeBSD AMI to build PHP 8.1

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#308]
The FreeBSD AMI needs to be updated to build PHP 8.0 (zts) and PHP 8.1 (zts, non-zts).

Acceptance Tasks:
[x] Update AMI documentation based on the changes made.
[x] Create a new AMI with updates with and appropriate name
[x] Update Jenkins

**Comment by zsistla** [comment]
Part of #327

**Comment by mfulb** [comment]
AMI has been integrated into CI/CD process and is working.
