### ISSUE TITLE
[PHP] Update Centos AMI to PHP 8.1

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#309]
The Centos AMI needs to be updated to build PHP 8.0 (zts) and PHP 8.1 (zts, non-zts).

Acceptance Tasks:
[ ] Update AMI documentation based on the changes made.
[ ] Create a new AMI with updates with and appropriate name
[ ] Update Jenkins

**Comment by zsistla** [comment]
Part of #327

**Comment by mfulb** [comment]
Candidate AMI has been created - waiting to integrate into CI/CD process.

**Comment by mfulb** [comment]
AMI has been integrated in CI/CD and can build the agent for PHP 8.1.
