### ISSUE TITLE
[PHP] Update Alpine/musl AMI to PHP 8.1

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#310]
The Alpine/musl AMI needs to be updated to build PHP 8.0 (zts) and PHP 8.1 (zts, non-zts).

Acceptance Tasks:
[ x] Update AMI documentation based on the changes made.
[ x] Create a new AMI with updates with and appropriate name
[ x] Update Jenkins

**Comment by zsistla** [comment]
Part of #327

**Comment by zsistla** [comment]
Alpine build node updated to build PHP 8.0 (zts) and PHP 8.1 (zts, non-zts).  New AMI integrated into jenkins and new PR job added to jenkins CI.  See MMF for details.
