### ISSUE TITLE
PHP8 MMF#2: Build Environment

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-php-agent#32]
This is part of multiple MMFs for PHP 8 work as outlined below.

[#33](https://github.com/newrelic/newrelic-php-agent/issues/33) MMF#1 [<ins>Agent with PHP 8 support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.hx9v342k5zzq)

[#32](https://github.com/newrelic/newrelic-php-agent/issues/32) MMF#2 [<ins>Build Environment with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy)

[#34](https://github.com/newrelic/newrelic-php-agent/issues/34) MMF#3 [<ins>Update Agent Tests with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.p2q7qbb5pbkr)

[#35](https://github.com/newrelic/newrelic-php-agent/issues/35) MMF#4 [<ins>Release Agent with PHP 8.0 Support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.et7wy5raaa9)

**Comment by tomfotherby** [comment]
We have delayed the rollout of PHP 8 on our fleet of webservers, waiting for support from the NewRelic PHP Agent. (Commented to ensure the `stale` :robot: knows this issue should be active)
