### ISSUE TITLE
Compiling against PHP 8.1 with gcc 9/10/11 under Ubuntu 20.04 LTS will fail

### ISSUE THREAD

**Issue by GwynethLlewelyn** [newrelic/newrelic-php-agent#321]
When attempting to compile the agent in Ubuntu 20.04 LTS using `gcc` (as opposed to using `clang`) will fail, because flags such as `-Wno-typedef-redefinition` aren't supported, and since the default is to flag all warnings as errors, an 'unsupported flag' is treated as such, thus preventing a successful compilation to finish.

## Description

Recent releases of PHP 8.1 unexpectedly have introduced some slight code sloppiness, which percolates up to the macros used in New Relic's PHP agent. `clang` seems not to mind much, as it respects the `-Wno-typedef-redefinition` flag, and, as such, considers this sloppiness merely a warning, and finishes compilation.

By sheer chance, in the past, I had successfully compiled the PHP agent for 7.3, 7.4 and 8.0, without any errors whatsoever, and hadn't even noticed which compiler was being used. I _do_ have _both_ `clang` and `gcc` installed, but I hadn't noticed that I systematically used `gcc` by default — and an end-of-life version, too (9.3.0, to be more precise). Since it did the job, I didn't notice anything wrong.

However, when attempting to compile the agent for PHP 8.1 under Ubuntu 20.04.3 LTS, there were a handful of errors, which could be clearly traced to flags that the compiler didn't recognise (`-Wno-typedef-redefinition` being the one that stuck in my head, but there were a handful of others). Apparently, when `gcc` encounters a flag that it doesn't accept, **and** a warning is triggered (for whatever reason — in my case, there were some inconsistencies with the declaration of functions and/or possible lack of array boundary checks), **then** `gcc` notices that it has an unsupported flag, and, because the default is to treat all warnings as errors, throws a fatal error and stops compilation. Interestingly, the compiler seems to 'understand' that the flag _is_ there, and assumes that it _may_ be overriding some warnings, but, since the flag is _not_ being recognised, `gcc` becomes very strict and terminates compilation, assuming that an 'unknown' flag that potentially masks a warning is sufficiently problematic to deal with — letting the programmer review what exactly was meant by throwing an error.

It's actually interesting, because this gets triggered _only_ when there is a warning which is not explicitly excluded to be ignored from 'turning into an error', so to speak. In other words, `config.m4` mandates that, by default, `-Werror` should be applied to _all warnings not explicitly excluded_, thus turning almost all warnings into errors. There is a handful of exceptions that the New Relic agent developers decided that could still be considered warnings and safely ignored. As such, when one of _those_ exceptions is found, the `gcc` compiler has no problem dealing with _those_. It's just when there is a condition that throws a _warning_ which is caught by the compiler that `gcc` seems to need to look up the list of warnings that are accepted as such, lists all the flags saying so, but finds a flag that it doesn't recognise — and, consequently, has no way to figure out if the thrown warning is to be excluded or not (in other words, the 'unknown flag' is believed to intend to mask one warning, but `gcc` does not _know_ if this is actually the case for that specific line or code — because the flag is unknown — so, by default, it aborts compilation, as indicated by `-Werror`). 

Because that behaviour is so weird — and also because it's been ages since I did some serious C/C++ compilations — I assumed that I had a bad setup at some point. So, the first thing I did was to check that `phpize` was doing its job properly, that every automatically generated file looked as it should, and so forth. Then I recompiled the whole agent code to work with PHP 7.3, 7.4, 8.0 — which had no problems whatsoever.

Finally, I replaced `gcc` 9.3.0; maybe it was simply too old to recognise some 'modern' flags. I bumped it to 10.X (available on the main repositories for Ubuntu Linux) with the same results: the errors might be differently phrased, but they essentially address the same problem. `gcc` 11.X is available from a development repository also hosted by Canonical, so I installed that in turn, did a clean compilation again, and got the same issue.

Now, I don't have access to many different systems and operating systems (my job is really _not_ doing code debugging!), but since it was reasonable to admit that I had a very broken Ubuntu installation (which, being a production machine, would take some time to be wiped clean and reinstalled...), so, as an experiment, I tried to compile things under macOS Big Sur (11.6.3). Because, by default, Apple uses its own variety of `clang` (which _is_ essentially `clang`...), the compilation worked flawlessly. This led me to test a `clang` compile under Ubuntu, with the same successful result.

The final check was to install `gcc` in my Mac, using `brew`,  which installs what it calls `Homebrew GCC 11.2.0_3`. And to confirm my assumption, it predictably failed to compile the NR agent for PHP 8.1. I still tried to do a compilation on my home Synology NAS (running a tailored Linux version for the arm64 architecture), but I lacked `phpize`, so I didn't pursue that approach further.

In any case, it was clear to me that `clang` had no issues with the  `-Wno-typedef-redefinition` flag, and respected it in all
situations where that warning was thrown, while `gcc` showed consistently the above behaviour.

Note that New Relic is not to blame (nor even, I suppose, the PHP core developers). There is a widely held assumption that if a compiler identifies itself as 'GNU C' (compatible), it _will_ respect the _same_ flags and overall quirks. Neither the `phpize`d code, nor New Relic's code have any reason to think otherwise. In fact, the `m4` macros included by `phpize` for PHP 8.1 do not even check if there is a difference between two allegedly 'GNU C'-compatible compiler toolchains.

And to make the issue more insane, when using the GNU tools (autoconf & friends), there is no _easy_ way to differentiate between `clang` and `gcc` (unlike what happens with CMake, where the test is trivial). The GNU autoconf repository, however, lists [a macro to do so](https://www.gnu.org/software/autoconf-archive/ax_compiler_vendor.html).

Because I love these kinds of puzzles, I'm submitting a new PR that temporarily fixes the issue. It's nothing more than a quick-and-dirty hack. As you can see, this is an issue that is not easily 'solved' by just changing the New Relic code: technically, it should involve the GNU C developers to change the behaviour of `-Werror` to deal with unknown flags in `gcc`; it involves the `clang` developers to get rid of non-compliant GNU C flags, or, at best, have an option to treat those in the same way as `gcc`; it involves the PHP core developers, who might wish to change the way `phpize` works under 8.1 (to add a built-in compiler vendor check and consider `clang`'s behaviour different from `gcc`), as well as, of course, fixing their own code so that it doesn't throw any warnings under `gcc`; and it may even involve the GNU autoconf tools developers, to add an _easier_ way to identify the compiler vendor with the standard installation, instead of the kludgy approach used with an additional macro (even if it's one in their own archives and thus 'official' to a certain degree).

That's way too much for me to do, so I'm sticking with a simple PR that fixes things for the New Relic PHP agent, and that's it :-)

Alternatively, you could simply add to the documentation that the NR PHP agent will only be successfully compiled under `clang` (and Apple's variant of it), and that `gcc`, for now, is not supported (until someone upstream, either GNU or the PHP devs, change _their_ code).

## Steps to Reproduce

1. Install `gcc` using the standard procedure for your particular operating system/distro, at least testing 9.4, 10.X, and 11.X.
2. Make sure you have the correct PHP toolset (including a functional `phpize`) for 8.1.
3. Download the `dev` branch of `newrelic-php-agent` (allegedly, this should work on the `main` branch as well, but since the `dev` branch is actively pursuing code cleanup to deal with PHP 8.1, it's safer that way) 
4. Make sure that, by default, `make` _is_ using `gcc` and not any other compiler (use the environment variable `$CC` to set it to the right path, or change it directly on the `Makefile`, etc.) 
5. Run `make` and watch the error messages.

Additionally: install `clang` and do the same (which will compile cleanly and flawlessly, even if some warnings will pop up now and then).

## Expected Behavior

* Since both `clang` and `gcc` announce themselves as being 'GNU C'-compatible, I would assume that both would respect _exactly_ the same compilation flags!
* PHP 7.3, 7.4, and 8.0 compile flawlessly under both `gcc` and `clang`, so there was no reason to expect to see any difference under 8.1
* While there might be a few 'rough edges' due to the 'newness' of 8.1 (as well as New Relic's own efforts to keep up with it), allegedly the building toolset ought at least to be able to deal with the most trivial issues (namely, if it's ok to ignore some type redefinitions as mere warnings under `clang`, there is no reason to believe that the compilation should be stricter under `gcc`)

## Relevant Logs / Console output

My apologies, I seemed to stupidly have deleted whatever logs I had. I _thought_ I had captured them in a file, but apparently I made a mistake somewhere... I'd be glad to set everything up once more from scratch, but at this very moment, I cannot promise to do it in the next few days (work deadlines coming up, holiday season, etc.....) 

## Your Environment

1. Ubuntu Linux server
  - Ubuntu 20.04.3 LTS
  - Linux kernel 5.4.0-91-generic
  - Bare-metal 4 core/8 thread Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz with 64 GBytes of memory and a 1TB disk (using RAID mirroring)
  - Compilers: gcc-9 (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, gcc-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, gcc-11 (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0, clang version 10.0.0-4ubuntu1
  - Tools: autoconf (GNU Autoconf) 2.69, automake (GNU automake) 1.16.1, m4 (GNU M4) 1.4.18
  - PHP 8.1.0, installed via [Ondřej Surý's PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php)
 
2. MacBook Pro
  - macOS Big Sur 11.6.3 (20G405)
  - Darwin Kernel Version 20.6.0
  - MacBook Pro (Retina, 15-inch, Mid 2014), 2.8 GHz Quad-Core Intel Core i7, 16 GB 1600 MHz DDR3, 500 GB Flash Storage (SSD)
  - Compilers: gcc-11 (Homebrew GCC 11.2.0_3) 11.2.0, Apple clang version 13.0.0 (clang-1300.0.29.30)
  - Tools: autoconf (GNU Autoconf) 2.71, automake (GNU automake) 1.16.5, GNU M4 1.4.6
  - PHP 8.1.1 (installed via Homebrew)

## Additional context

As said, I'm no professional programmer, much less a C/C++ programmer, but a humble sysadmin who tinkers with code for pleasure and fun — also, I'm _very_ rusty with all the ensemble of GNU tools, to the best of my recollection I haven't done anything _serious_ with them since, uh, 1994 or so.

As a consequence, I might be misrepresenting a lot of things, and overlooking others, and I'm pretty sure that the PR I'm going to submit next could be done in a much better way — I'll leave that to the experts!

**Comment by Ak-x** [comment]
@GwynethLlewelyn can you test this on the latest agent version, and confirm if you are still having this issue?

**Comment by GwynethLlewelyn** [comment]
Agreed, let's close another one!
