### ISSUE TITLE
Latest agent download does not include aarch64 support

### ISSUE THREAD

**Issue by mike503** [newrelic/newrelic-php-agent#323]
As of agent 9.18 there is aarch64 support (ARM and Graviton 2 support) but the installer

## Description

I would have expected when the agent supported the arch it'd be packaged in precompiled into the easy installer, maybe this is just a simple overlook!

## Steps to Reproduce

Using a container on an aarch64 host, [this snippet](https://discuss.newrelic.com/t/relic-solution-php-agent-and-daemon-containers/84841) should work, but I realized it didn't on my Graviton 2 based systems - it winds up installing the amd64 version of the agent, not the aarch64 version - the agent directory in the archive doesn't include aarch64.

```
RUN curl -L "https://download.newrelic.com/php_agent/archive/${NEW_RELIC_AGENT_VERSION}/newrelic-php5-${NEW_RELIC_AGENT_VERSION}-linux.tar.gz" | tar -C /tmp -zx \
 && export NR_INSTALL_USE_CP_NOT_LN=1 \
 && export NR_INSTALL_SILENT=1 \
 && /tmp/newrelic-php5-*/newrelic-install install \
 && rm -rf /tmp/newrelic-php5-* /tmp/nrinstall*
```

## Expected Behavior

The agent directory would be populated with aarch64 and the scripting to detect the arch would find it and select it properly.

## Your Environment

Relevant Dockerfile specifics:

```
FROM ubuntu:bionic

ENV NEW_RELIC_AGENT_VERSION 9.18.1.303
ENV PHP_VERSION 7.4
```

Currently compiling the agent by hand using [these instructions](https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64/) which winds up looking like this in the end:

```
RUN apt-get update && apt-get install -y git golang libpcre3-dev php${PHP_VERSION}-dev && \
  curl -L -o /tmp/v${NEW_RELIC_AGENT_VERSION}.tar.gz https://github.com/newrelic/newrelic-php-agent/archive/refs/tags/v${NEW_RELIC_AGENT_VERSION}.tar.gz && \
  cd /tmp && \
  tar xfz v${NEW_RELIC_AGENT_VERSION}.tar.gz && \
  cd newrelic-php-agent-${NEW_RELIC_AGENT_VERSION} && \
  git init && \
  make && \
  make agent-install && \
  mkdir -p 0777 /var/log/newrelic && \
  rm -rf /tmp/v${NEW_RELIC_AGENT_VERSION}.tar.gz /tmp/newrelic-php-agent-${NEW_RELIC_AGENT_VERSION} && \
  phpenmod newrelic
```

Note: I wanted to use Ubuntu Focal, but I think something is awry with that image (unrelated to this)

## Additional context

I would have expected when the agent supported the arch it'd be packaged in precompiled into the easy installer, maybe this is just a simple overlook.

**Comment by mike503** [comment]
also just noticed that https://hub.docker.com/r/newrelic/php-daemon doesn't have the aarch64 build pushed either. That relies on this, so this effectively blocks that from being officially supported too.

**Comment by mbackonja** [comment]
Any updates on this one?

Will newrelic publish a new version with aarch64 installer?

Did someone manage to install New Relic PHP Agent inside Alpine Linux on graviton2 CPU?

**Comment by zsistla** [comment]
Hello and thank you all for your feedback.

ARM64 support for the New Relic PHP Agent (and daemon) has been available since 9.18.1; however, it is currently *only* available via compiling from source, please see the installation instructions for more details:
https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64/

We agree a downloadable tarball of binaries and integration with the installer and an arm64 dockerized daemon are great to have, and these features will be addressed in a later release.

**Comment by AlecRust** [comment]
Right, so Ubuntu 22.04 ARM64 (aarch64) is not supported at all, even building from source 🙁

**Comment by Winfle** [comment]
Hello, do we have possibility to compile newrelic for PHP 7.X and linux/arm64?

**Comment by acasademont** [comment]
Having the arm64 tarballs would be amazing, right now it's a bit complicated to have our Dockerfiles compile the binaries.

**Comment by 65** [comment]
Would love to see support for Ubuntu 22.04 ARM64 (aarch64)

**Comment by csandanov** [comment]
Considering you cannot compile newrelic (#456) with the gcc 11+ it would be great to have arm64 tarballs

**Comment by esolitos** [comment]
I understand that a simple **+1** is typically not very helpful, but I am wondering if this is even something that we can expect to happen at any point or not.

I wonder this because this issue is now over 1 year old and there has not been a single official answer from the Newrelic team, and as a paying customer of NewRelic I would like to understand if I should just plan to move away from Ubuntu on ARM64 if I want to use `newrelic-php5` or if I can expect to have support at some point.

**Comment by Ak-x** [comment]
Thank you for your feedback.
While we can't provide a precise timeline, arm64 support is within our roadmap, in progress and expected to be included in an upcoming release.

**Comment by esolitos** [comment]
Thank you for the answer, at the least this clarify the situation.

**Comment by xocasdashdash** [comment]
hi there! 
was wondering if there's any news about the ARM64 support? right now our build times are heavily impacted by the lack of an arm64 extension

**Comment by aquilinux** [comment]
@Ak-x any update on this? We strong rely on newrelic-install being available for arm64. thanks!

**Comment by Ak-x** [comment]
Hello @aquilinux , @xocasdashdash, Arm64 packaging and binaries are within our top priorities, this is currently in progress, and we expect it to be available in our upcoming releases.

**Comment by esolitos** [comment]
Awesome news, thanks for the feedback! 😊 Message ID: ***@***.***>

**Comment by ruudk** [comment]
It is supported now 🥳🥳🥳
https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.10.0.1

**Comment by zsistla** [comment]
ARM64 binaries provided in PHP Agent release [10.10.0.1](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-10-0-1/).

**Comment by luckyraul** [comment]
Still not available in the apt repo

**Comment by Ak-x** [comment]
Thank you for the feedback @luckyraul; we currently only provide arm64 binaries via tarballs, reference: https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64/

We can consider this for a feature request, cc: @ak-war.
