### ISSUE TITLE
Epic: Php 8.1 Agent Deployment

### ISSUE THREAD

**Issue by Ak-x** [newrelic/newrelic-php-agent#327]
The code changes related to 8.1 are complete, our team is working with priority through the deployment details in order to release 8.1.  This Epic handles specifically the deployment of 8.1.

**Comment by deefour** [comment]
@Ak-x hate to ask because I think I've seen an estimate in New Relic docs but can't find it now: do you have an expected date for 8.1 support?

**Comment by icanhazstring** [comment]
> @Ak-x hate to ask because I think I've seen an estimate in New Relic docs but can't find it now: do you have an expected date for 8.1 support?

https://github.com/newrelic/newrelic-php-agent/issues/177#issuecomment-1004747677

**Comment by rvanlaak** [comment]
@Ak-x given this issue's title, and the fact that several issues mention this issue as the EPIC, would it be an idea to put a list of these issues in this issue's description to track progress? 
Many of us are waiting on PHP8.1 support for the php-agent, so would be great if we can manage expectations.

**Comment by porozhnyy** [comment]
Guys, with the beginning of March you! I just want to remind you that we're still waiting...

**Comment by Ak-x** [comment]
Hello all, @ak-war  has posted the latest update here: https://github.com/newrelic/newrelic-php-agent/issues/258#issuecomment-1050343032.

> We would like to assure you that our team is working hard on the PHP 8.1 support items and this is our top priority. We are looking to release PHP 8.1 support by 9th March 2022.

**Comment by Ak-x** [comment]
> @Ak-x given this issue's title, and the fact that several issues mention this issue as the EPIC, would it be an idea to put a list of these issues in this issue's description to track progress? Many of us are waiting on PHP8.1 support for the php-agent, so would be great if we can manage expectations.
> 
> Or should we follow https://github.com/newrelic/newrelic-php-agent/milestone/11 ? The milestone does not allow leaving comments though.

@rvanlaak I appreciate the feedback; this Epic was split for internal purposes. Going forward I will add descriptions on our Epics in the scenario that we partition them. 👍

**Comment by rvanlaak** [comment]
Seems that a PHP 8.1 supporting agent was released yesterday? 🎉  https://github.com/newrelic/newrelic-php-agent/releases/tag/v9.19.0.309
