### ISSUE TITLE
PHP8 MMF#3: Agent tests

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-php-agent#34]
This is part of multiple MMFs for PHP 8 work as outlined below.

[#33](https://github.com/newrelic/newrelic-php-agent/issues/33) MMF#1 [<ins>Agent with PHP 8 support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.hx9v342k5zzq)

[#32](https://github.com/newrelic/newrelic-php-agent/issues/32) MMF#2 [<ins>Build Environment with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy)

[#34](https://github.com/newrelic/newrelic-php-agent/issues/34) MMF#3 [<ins>Update Agent Tests with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.p2q7qbb5pbkr)

[#35](https://github.com/newrelic/newrelic-php-agent/issues/35) MMF#4 [<ins>Release Agent with PHP 8.0 Support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.et7wy5raaa9)

**Comment by jodeev** [comment]
Comment added by Jodee Varney in Aha! - [View](https://newrelic.aha.io/comments/6935915661586451969)

lot of work hidden in failing tests which is difficult to estimate until we start fixing them.

**Comment by ostrolucky** [comment]
What's the status here? PHP8 support is stuck on this task, but there are no updates here since 4th March. Referenced issues here are not any better.

Also, is this task really about tests only, or this is the task where actually whole work of making the extension work with PHP 8 is being done? Otherwise I miss issue in MMFs where this work is done...

**Comment by joshuabenuck** [comment]
#106, #107, and #114 are nearing completion. #129 was recently added based on some discoveries made in some of the other tickets.

The work to get the core of the agent compatible with PHP 8 is already done (and was completed in previous MMFs). The tasks here are to ensure that we validate the agent against various operating systems, PHP versions, and frameworks. Some of that validation identified additional needed changes in the build systems, tests, and sometimes even the agent itself.

This has taken us longer than we anticipated and we know everyone is anxious to see it completed. Please know that we are doing everything we can to release a PHP 8 compatible agent as soon as possible.
