### ISSUE TITLE
Add 9.19.0 release notes

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#341]
Create a draft of the `v9.19.0.303` release notes on[ GitHub](https://github.com/newrelic/newrelic-php-agent/releases) and a PR on the [new relic docs website](https://github.com/newrelic/docs-website). For the docs website process, see the [contributing docs](https://github.com/newrelic/docs-website/blob/develop/CONTRIBUTING.md) for more information.

**Comment by mfulb** [comment]
Part of #327.

**Comment by misiekn** [comment]
Opened [#6380](https://github.com/newrelic/docs-website/pull/6380) for PHP agent release 9.19.0 updates to docs-website.
