### ISSUE TITLE
Modify agent upgrade process to handle unsupported PHP installations

### ISSUE THREAD

**Issue by mfulb** [newrelic/newrelic-php-agent#349]
The 9.19.0 release will not contain support for PHP 5.3 and 5.4 which have been EOLed previously.  When upgrading the agent on systems with these versions of PHP installed the process should not allow any existing agent for these PHP versions to be removed.  The upgrade process should stop with a notification explaining the scenario and explain that additional steps will be required to upgrade the agent.

**Comment by zsistla** [comment]
PHP 5.3 and PHP 5.4 support was deprecated in release [9.15](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9150293) of the agent, and removed in release [9.17](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-9170300/).

**Comment by mfulb** [comment]
RPM spec files have been modified to prevent upgrade on a system with a PHP version 5.3 or 5.4 detected on the standard PATH.
