### ISSUE TITLE
PHP8 MMF#4: Release agent w basic PHP8 support

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-php-agent#35]
For this release with bare bones support for PHP8, we will be documenting special application and agent configuration requirements to allow deployment of the agent in PHP8 environments. We will not be supporting the new JIT capabilities of PHP8.

This is part of multiple MMFs for PHP 8 work as outlined below.

[#33](https://github.com/newrelic/newrelic-php-agent/issues/33) MMF#1 [<ins>Agent with PHP 8 support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.hx9v342k5zzq)

[#32](https://github.com/newrelic/newrelic-php-agent/issues/32) MMF#2 [<ins>Build Environment with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy)

[#34](https://github.com/newrelic/newrelic-php-agent/issues/34) MMF#3 [<ins>Update Agent Tests with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.p2q7qbb5pbkr)

[#35](https://github.com/newrelic/newrelic-php-agent/issues/35) MMF#4 [<ins>Release Agent with PHP 8.0 Support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.et7wy5raaa9)

**Comment by adhocore** [comment]
waiting for newrelic support on php8 - this is the only blocker we have to jump from php7.4 to php8.0 in our app :)

**Comment by jodeev** [comment]
We hear you. We are very sorry that we are holding you up. Please bear with us, we are making good progress and anticipate being able to release our initial support for php 8 soon.

**Comment by Swop** [comment]
Any news on this?

I really appreciate the effort (I'm sure it is not an easy upgrade), but it's been a month since the last update from the team, and PHP8 is officially out for 4 months...

I believe that most folks around the globe are now ready to ship the upgrade to their production systems, but are blocked by the missing NewRelic update.

Also, I'm a bit afraid when I'm seeing a bunch of stale PHP8 support tickets still lying around the "TODO" list in your roadmap.

**Comment by ruudk** [comment]
Same here, we're blocked by NewRelic before we can rollout PHP 8.0. Already in October me and others told NR on the forum about PHP 8 approaching soon and here we are.

**Comment by zsistla** [comment]
Thank you for your continued patience and interest, and we are continuing to prioritize and work diligently on this in order to unblock you as soon as possible.  :) We are as eager to get this released as you are!

The significant changes in PHP 8 required a multi-step effort.  Having finished step 1(#33) and step 2(#32) , we are currently in step 3(#34) which is the rigorous testing phase in order to ensure utmost quality and stability when we release for step 4 (#35).

**Comment by pascaldevink** [comment]
I think some of the issues stem from low communication from the NR side on the expected roadmap. Yes there are these issues, but they provide no information at all, only links to closed-to-public google docs

**Comment by mcascardi** [comment]
Subscribed to notifications on this!  I'm not in a rush as other web apps are still developing full support for PHP 8 but it will become the default version soon!

**Comment by ErnestStaug** [comment]
Because of slow implementation our company switched to competitor as we couldn’t wait much longer... will subscribe to see if you will be able to achieve php8 support this year :)

**Comment by ruudk** [comment]
@ErnestStaug which one? Would love to switch as well

**Comment by tomfotherby** [comment]
Our NewRelic contract ends in a few months. We will move too. We are thinking to try Sentry.io .

**Comment by lptn** [comment]
our company will wait for 1week more, if not — we will move too. We are thinking about bugsnag + prometheus + grafana

**Comment by adri** [comment]
The tracer by DataDog has added full PHP 8 support already on Nov 30, 2020 (APM and distributed tracing).
https://github.com/DataDog/dd-trace-php/releases/tag/0.52.0

**Comment by ErnestStaug** [comment]
> @ErnestStaug which one? Would love to switch as well

We use sentry And now adding DataDog :)

**Comment by AlexGodbehere** [comment]
Any update on this @jodeev? We were ready to roll out PHP8 until realizing that the NR agent doesn't support it! Shocked that this hasn't been released yet.

**Comment by jodeev** [comment]
We're close! But still a couple of weeks. We're in the final stages,
updating build + test environments. We are really pained that it is taking
longer than anticipated, and truly sorry for the delays that this is
causing others. Please hang on just a little longer 🙏

**Comment by elnur** [comment]
It's time to consider an alternative as well, I guess.

**Comment by tomfotherby** [comment]
@jodeev  - I appreciate the update. A long time coming... but appreciated nonetheless.

**Comment by AlexGodbehere** [comment]
Thanks @jodeev, I appreciate the update. We're eagerly waiting.

**Comment by sander3** [comment]
I would like to know the exact release date as the last "few weeks" are also almost over. I would also like to know how you plan to improve the release schedule for future releases. It is not the first time you have taken months after a major release and I would like to know if it is now worth the investment to move over to a competitor. The current release schedule is unacceptable.

**Comment by seanhamlin** [comment]
This is impacting the ability for our customers to switch to PHP8, as currently they loose New Relic APM in the process. Keen for an update @jodeev!

**Comment by AlexGodbehere** [comment]
@jodeev - we'd all really appreciate an update here. Are you still on track for release this week?

**Comment by jodeev** [comment]
Hi @AlexGodbehere, I've recently left New Relic, @zsistla can you weigh in here?

**Comment by kneitinger** [comment]
@AlexGodbehere final release testing is happening this week.  Due to the size of the release, we don't feel comfortable releasing later in the week, so the formal release process will start early next week!

**Comment by AlexGodbehere** [comment]
Great news @kneitinger, looking forward to it. Please could you update us on here when it's available?

**Comment by AlexGodbehere** [comment]
Hi @kneitinger - any update on this?

**Comment by kocherovf** [comment]
It seems they will release it tomorrow.

https://github.com/newrelic/docs-website/pull/1900

**Comment by sander3** [comment]
```
* New Relic recommends that you upgrade the agent regularly and at a minimum every 3 months. As of this release, the oldest supported version is [8.6.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-860238/).
```
😆

**Comment by kneitinger** [comment]
Good eye @kocherovf 😄 

Yep @AlexGodbehere, targeting a release tomorrow (4/21) in the morning (PST)!

@sander3 touché 😅

**Comment by kneitinger** [comment]
And, furthermore, thank you for all of your patience ❤️ 

I know this was a long wait for everyone, and it no doubt was stressful to have to keep checking in on this status. This work accompanied, and necessitated, a lot of internals work, both in the code, and in our team infrastructure, which ultimately sets us up way better for efficiency, testing confidence, and iteration in subsequent work, but at the end of the day, we recognize that despite those long term improvements, in the short term, we had you waiting.  I apologize for that, and look forward to making you all upgrade every 3 months at a minimum from here on out 😄

**Comment by kneitinger** [comment]
[PHP Agent 9.17](https://github.com/newrelic/newrelic-php-agent/releases/tag/v9.17.0.300) has been released 👍

**Comment by seanhamlin** [comment]
In case anyone else is confused the actual release version is `9.17.0.300` - see https://download.newrelic.com/php_agent/archive/9.17.0.300/

**Comment by ralt** [comment]
Hi there,

It seems that the release is not compatible with the ZTS release of php8, most probably because upstream has changed the flag from `--enable-maintainer-zts` to `--enable-zts`. Could you double check?

**Comment by joshuabenuck** [comment]
> Hi there,
> 
> It seems that the release is not compatible with the ZTS release of php8, most probably because upstream has changed the flag from `--enable-maintainer-zts` to `--enable-zts`. Could you double check?

@ralt You are correct. I found a warning in a build log on our libc based nodes about `--enable-maintainer-zts` not being a recognized option which led to our PHP 8.0 ZTS builds being non-ZTS builds. I have opened issue #172 to track this.

**Comment by ralt** [comment]
Thanks!
