### ISSUE TITLE
Out of memory - causing intermittent 502 response errors

### ISSUE THREAD

**Issue by enricopesce** [newrelic/newrelic-php-agent#351]
## Description
I have tested the latest agent version newrelic-php5-9.18.1.303
on my server with PHP 7.2.24-0ubuntu0.18.04.7 on Ubuntu 18.04.5 LTS

The APM module uses the default .ini settings, I have only added my KEY and AppName.

I enabled the APM and the CPU and memory usage are increased rapidly, some applications have started to generate "Out of memory errors" never generated before!

I read on the New Relic forum some memory leak bugs but seems solved with the 9.18.1 agent version, in my case the bug is still present.

How I can help to fix the problem? thank you!

**Comment by zsistla** [comment]
Hi @enricopesce ,

Thanks for trying out New Relic and sorry to hear you've been having issues with the PHP agent.

Here's a great post regarding things that can cause overhead issues with the PHP agent:
https://discuss.newrelic.com/t/relic-solution-php-agent-cpu-overhead-tips/70182

One thing you can try right away is to check the clocksource (the above link describes how to check and change if needed).  This is often the culprit of unexplained overhead.

Please try that and let us know how it goes.

**Comment by enricopesce** [comment]
Hi @zsistla thank you for the support! I've read the post, in my case I use TSC as default.

In detail, after other tests, I discovered that CPU is not the problem but is the memory.

When the agent (version 9) is enabled the PHP scripts use all my RAM and swap memory, so the scripts go in "Out of memory" errors.
