### ISSUE TITLE
Agent build fails with error: unannotated fall-through between switch labels on macOS Monterey

### ISSUE THREAD

**Issue by themazim** [newrelic/newrelic-php-agent#354]
## Description

Building php Agent on macOS Monterey (Version 12.2 (21D49) ) on m1 macbook (ARM64) fails due to error:

## Steps to Reproduce

execute `make` to build the agent on macOS m1

## Expected Behavior

Build should not fail. 

## Relevant Logs / Console output

```
[...]
cc -DNR_SYSTEM_DARWIN=1 -DHAVE_BACKTRACE=1 -DHAVE_DEV_FD=1 -DHAVE_PTHREAD_MUTEX_ERRORCHECK=1  -std=gnu99 -fPIC -DPIC -pthread -Wall -Werror -Wextra -Wbad-function-cast -Wcast-qual -Wdeclaration-after-statement -Wformat -Wformat-security -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wno-write-strings -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-enum -Wbool-conversion -Wempty-body -Wheader-hygiene -Wimplicit-fallthrough -Wlogical-op-parentheses -Wloop-analysis -Wsizeof-array-argument -Wstring-conversion -Wswitch -Wswitch-enum -Wuninitialized -Wunused-label -Wno-typedef-redefinition -Wno-missing-field-initializers -I/opt/homebrew/Cellar/pcre/8.45/include -I/private/tmp/newrelic-php-agent/vendor/local/include  -O0 -g3 -DENABLE_TESTING_API -MMD -MP -c util_json.c -o util_json.o
cc -DNR_SYSTEM_DARWIN=1 -DHAVE_BACKTRACE=1 -DHAVE_DEV_FD=1 -DHAVE_PTHREAD_MUTEX_ERRORCHECK=1  -std=gnu99 -fPIC -DPIC -pthread -Wall -Werror -Wextra -Wbad-function-cast -Wcast-qual -Wdeclaration-after-statement -Wformat -Wformat-security -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wno-write-strings -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-enum -Wbool-conversion -Wempty-body -Wheader-hygiene -Wimplicit-fallthrough -Wlogical-op-parentheses -Wloop-analysis -Wsizeof-array-argument -Wstring-conversion -Wswitch -Wswitch-enum -Wuninitialized -Wunused-label -Wno-typedef-redefinition -Wno-missing-field-initializers -I/opt/homebrew/Cellar/pcre/8.45/include -I/private/tmp/newrelic-php-agent/vendor/local/include  -O0 -g3 -DENABLE_TESTING_API -MMD -MP -c util_logging.c -o util_logging.o
util_hash.c:198:5: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
    case 2:
    ^
util_hash.c:198:5: note: insert '__attribute__((fallthrough));' to silence this warning
    case 2:
    ^
    __attribute__((fallthrough));
util_hash.c:198:5: note: insert 'break;' to avoid fall-through
    case 2:
    ^
    break;
util_hash.c:201:5: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
    case 1:
    ^
util_hash.c:201:5: note: insert '__attribute__((fallthrough));' to silence this warning
    case 1:
    ^
    __attribute__((fallthrough));
util_hash.c:201:5: note: insert 'break;' to avoid fall-through
    case 1:
    ^
    break;
2 errors generated.
make[1]: *** [util_hash.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [axiom] Error 2
make: *** Waiting for unfinished jobs....
```

## Your Environment

NR Release: v9.19.0.309
PHP 8.1.2
Macbook m1 pro 
macOS Monterey Version 12.2 (21D49)

## Additional context

I would assume this is not only linked to macOS but rather to specific compiler versions.

Workaround:

comment/remove line `AXIOM_CFLAGS += -Wimplicit-fallthrough` in `./axiom/Makefile` solves the issue and builds the client just fine.

This seems to be related to different gcc version and how they handle fallthrough ( https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7 ) 

Building the agent under ARM64 with debian works just fine. 

Unfortunately, I am not very familiar with C or the consequences this change implicates. 

Currently testing newrelic on m1 php8.1  and it seems to work so far.

**Comment by zsistla** [comment]
Hello and thanks for reaching out.  Unfortunately we discontinued MACOS support January 2021.
Please see the following for compatibility and supported operating systems.
https://docs.newrelic.com/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements/

I see you are using the M1, if you are interested in arm64, please see the link about arm64 installation:
https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64/

**Comment by themazim** [comment]
@zsistla Hey, thanks for your answer, as mentioned, I assume this is *not* solely bound to macOS.

**Comment by zsistla** [comment]
Thanks for your additional investigation and for posting your workaround for this issue!

**Comment by zsistla** [comment]
What compiler version were you using?
