### ISSUE TITLE
PHP 8.1 FPM: Missing curl tracking 

### ISSUE THREAD

**Issue by adri** [newrelic/newrelic-php-agent#355]
## Description

After deploying the New Relic agent v9.19.0 with PHP 8.1 we noticed that the curl integration seems to not track durations and throughput anymore when running under FPM. It works still when in the context of PHP CLI (worker). This worked under PHP 8.1 using New Relic Agent version v9.19.0.

## Steps to Reproduce

1. Upgrade to v9.19.0 using PHP 8.0 ✅ curl tracked correctly
2. Upgrade to v9.19.0 using PHP 8.1 ❌  curl not tracked correctly.

## Expected Behavior

Curl response duration tracking should stay the same as under PHP 8.1.

## Relevant Logs / Console output
<img width="688" alt="Screen Shot 2022-03-03 at 14 59 41" src="https://user-images.githubusercontent.com/133832/156581717-7373dc13-1d97-4a53-8771-fc4934e6b321.png">

However, throughput didn't change:   
![Screen Shot 2022-03-03 at 15 10 31](https://user-images.githubusercontent.com/133832/156581226-3143cd48-8918-4fff-b821-91acbefc1289.png)

## Your Environment

* Offical `php:8.1.3-fpm` Docker image with Linux 5.4.172-90.336.amzn2.x86_64 x86_64 GNU/Linux

**Comment by zsistla** [comment]
@adri Thanks for bringing this to our attention.
We'll be investigating it on our side and will reach out if we need any clarifications/additional info from you.

**Comment by zsistla** [comment]
Hi @adri ,
If you could provide a snippet of the code that makes the curl call and also the framework being used for the website, it'll help us reproduce/debug this.
:) Thanks!

**Comment by adri** [comment]
@zsistla Good point! I assumed that we use a released version of Guzzle (which uses afaik `curl_multi_exec`). However, we seem to use a version that fixes an PHP 8.1 deprecation that is not merged and released yet. 

* https://github.com/guzzle/guzzle/pull/2991

Could this be related?

**Comment by adri** [comment]
I guess this issue can be closed and only becomes relevant when this PR is actually merged.

**Comment by zsistla** [comment]
@aldri, oh interesting!  Thanks for the PR link and the update on this.

**Comment by ostrolucky** [comment]
We use Guzzle 7.4.3 and we updated to PHP 8.1 , now after latest release it seems NR no longer accurately measures external calls

![image](https://user-images.githubusercontent.com/496233/170992881-826aad8c-4d01-44de-900e-52aa7a7594df.png)

**Comment by fastyzfr1** [comment]
We recently upgraded to PHP 8.1 from 7.4 and all of our external calls are not being tracked. We are using Laravel 9.x which uses Guzzle as well.
