### ISSUE TITLE
P17: Entity identity

### ISSUE THREAD

**Issue by ak-war** [newrelic/newrelic-php-agent#358]
**Summary** : Collect new linking context data like IP address and long hostname in the existing utilization blob.

**Specs** : [https://source.datanerd.us/agents/agent-specs/pull/360](https://source.datanerd.us/agents/agent-specs/pull/360)  
  
  
**Supporting docs** :

- [https://newrelic.jiveon.com/groups/agents-community-of-practice/blog/2018/10/25/linking-apm-and-infrastructure-data](https://newrelic.jiveon.com/groups/agents-community-of-practice/blog/2018/10/25/linking-apm-and-infrastructure-data)
- [https://docs.google.com/document/d/1bvBnvDrx\_uhOX6H6Z\_vlZJrB2ByT6QswR0Ij9cbB0pk/edit#heading=h.6keeflqrxaph](https://docs.google.com/document/d/1bvBnvDrx_uhOX6H6Z_vlZJrB2ByT6QswR0Ij9cbB0pk/edit#heading=h.6keeflqrxaph)
- [https://docs.google.com/document/d/1qekIq8VKkKPeQbcJiV4vbJVZTgXWFMgqdfRgxpYmfM4/edit#heading=h.73f6rbo94w8u](https://docs.google.com/document/d/1qekIq8VKkKPeQbcJiV4vbJVZTgXWFMgqdfRgxpYmfM4/edit#heading=h.73f6rbo94w8u)

**Comment by misiekn** [comment]
Covered by #414, #415, #416, and #417.
