### ISSUE TITLE
Test Configurable span reservoir sizes

### ISSUE THREAD

**Issue by ZNeumann** [newrelic/newrelic-php-agent#365]
Add tests that confirm changeability of span reservoir sizes

**Comment by zsistla** [comment]
This should create test cases for the ini value created in #364 that adhere's to the agent spec's naming scheme.

There are currently 2 cases that newrelic.special.max_span_events: 
newrelic-php-agent/tests/integration/span_events/test_span_events_special_max*.php
These need to be modified for the name change and expanded.

**Comment by zsistla** [comment]
Part of #206
