### ISSUE TITLE
Deprecate CAT

### ISSUE THREAD

**Issue by ZNeumann** [newrelic/newrelic-php-agent#368]
Currently the ini has:
```
; Setting: newrelic.cross_application_tracer.enabled
; Type   : boolean
; Scope  : per-directory
; Default: true
; Info   : Enables or disables support for Cross Application Tracing, aka "CAT".
;
;newrelic.cross_application_tracer.enabled = true
```

Add deprecation notice to the file.
Set the default to false both in the ini file and the php_nrini.c file.

- [x] Change ini file default to "false" and add deprecation notice
- [x] Code changes to set default to false
- [x] Code to output deprecation warning to log when agent detects CAT enabled
- [x] New tests as needed
- [x] Update existing tests as needed

**Comment by mfulb** [comment]
Work complete with PR #401.
