### ISSUE TITLE
Agent installation on docker debian from Apple M1

### ISSUE THREAD

**Issue by nitneuk** [newrelic/newrelic-php-agent#396]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Hi everyone, 

I tested multiple times to install php agent on a docker php debian image, but it don't seems to work on my machine (mac M1), while it works perfectly on my coworkers computers (mac intel, ubuntu, etc)

## Steps to Reproduce

Run on Apple M1 : 
```
docker run -it --rm php:8.1.3-fpm-buster sh -c 'curl -L https://download.newrelic.com/php_agent/archive/9.19.0.309/newrelic-php5-9.19.0.309-linux.tar.gz | tar -C /tmp -zx && NR_INSTALL_USE_CP_NOT_LN=1 /tmp/newrelic-php5-*/newrelic-install install && php -m |grep relic'
```
I added a real license key, when asked during installation. 
Then on `php -m |grep relic` I got : 
```
Warning: PHP Startup: Unable to load dynamic library 'newrelic.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

The newrelic extension is not loaded, however `/usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so` exists. 

I also tried to install it from a debian package (`.deb`) but it does not work as well, as no `arm64` package is available.

## Expected Behavior

The newrelic extension should be properly loaded. 
`php -m |grep relic` should print `newrelic`

## Your Environment

Macbook Pro 13, Apple M1, MacOs 12.2.1

Tested with docker versions  :
- Docker version 20.10.12, build e91ed57
- Docker version 20.10.13, build a224086

**Comment by rvanlaak** [comment]
Same here, but with Alpine on M1. See https://github.com/newrelic/newrelic-php-agent/issues/383

**Comment by ZNeumann** [comment]
Hello! Unfortunately, at this time we do not release binaries for Arm64. For information on how to install New Relic on Arm64, see [here](https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64). It also appears that the install script does not detect when attempting to install on an incorrect architecture- thank you for bringing that to our attention. That can be tracked [here](https://github.com/newrelic/newrelic-php-agent/issues/397).

**Comment by rvanlaak** [comment]
Oh that is interesting, because issue https://github.com/newrelic/newrelic-php-agent/issues/323 does seem to mention that: 

> As of agent 9.18 there is aarch64 support (ARM and Graviton 2 support) [...]

**Comment by ZNeumann** [comment]
Hello @rvanlaak , to be clear, we do support the PHP Agent on Arm64. We just do not yet release Arm64 binaries. So to get the agent on an Arm64 machine, it must be [compiled from source](https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64).

**Comment by nitneuk** [comment]
Thanks for replying @rvanlaak @ZNeumann , and for the workaround 👍

**Comment by NiklasBr** [comment]
@ZNeumann any updated plans on releasing arm64 binaries?

**Comment by ZNeumann** [comment]
Hi @NiklasBr , there are arm64 binaries available: https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64/#tarball-installation

**Comment by NiklasBr** [comment]
> We just do not yet release Arm64 binaries

**Comment by ZNeumann** [comment]
Arm64 binaries have been available since [release 10.10](https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.10.0.1). I apologize that this ticket was not updated with the new information.

**Comment by NiklasBr** [comment]
@ZNeumann why are you not offering the same installation path as for other architectures? The means that we still cannot properly create a single `Dockerfile` which works on multiple CPU architectures.

**Comment by ZNeumann** [comment]
[This comment](https://github.com/newrelic/newrelic-php-agent/issues/706#issuecomment-2077632855) provides a Dockerfile layer that adds latest New Relic PHP agent to your PHP application container image. That layer is independent of the architecture and Linux distribution (except for Alpine) because it uses tarball install, which includes binaries for all supported PHPs and architectures.

**Comment by NiklasBr** [comment]
When will it be added to the official documentation as a supported and normal way of installing the agent?

**Comment by lavarou** [comment]
> When will it be added to the official documentation as a supported and normal way of installing the agent?

@NiklasBr The official documentation has been updated. Here's the link to updated example [`Dockerfile`](https://docs.newrelic.com/docs/apm/agents/php-agent/advanced-installation/docker-other-container-environments-install-php-agent/#dockerfile-example) (it is collapsed and needs to be clicked to reveal).

**Comment by DracoBlue** [comment]
fyi at https://github.com/shivammathur/homebrew-extensions/pull/4106 I added brew .so files for newrelic on macosx. it does include only a small patch to make the protobuf library https://github.com/shivammathur/homebrew-extensions/pull/4106/files#diff-ec2f50cae97d8aa0279d74ba8ba1f0d8fc2d86a9439b155ac778f3432877277bR46 - maybe it's possible to patch this upstream :)
