### ISSUE TITLE
PHP 8 - Repair Laravel segfault when using `jit=1255`

### ISSUE THREAD

**Issue by kneitinger** [newrelic/newrelic-php-agent#40]
## Summary
Internal testing shows that Laravel tests segfault when using `jit=1255`.  For this issue, repair any and all segfaults when using `1255`, and if current tests do not adequately cover these cases, add such tests the the appropriate suite.

## Desired Behavior

Laravel based applications do not trigger segmentation faults when `jit=1255`

## Additional context

- [PHP 8 JIT Source](https://github.com/php/php-src/tree/master/ext/opcache/jit)
- Internal team mobbing session `gdb` walkthrough

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by zsistla** [comment]
A change going into 8.0.1 will *disable* JIT for third party extensions that override zend_execute_ex (we do).
https://github.com/php/php-src/commit/d5a82e2c4eebe8337ff7790db46d812af2fbcec9#diff-9faa6c4e1812bb88ee722439bfa2d0b48c8034871c2a625e00d14e6dbfbb835cR4180

An alternative might be a new `Observer API` that is supposed to help with this:
Observer api: https://github.com/php/php-src/pull/5857

After pulling down the 8.0.1 change and recompiled PHP and our agent.
After running PHP-CLI with our agent, it no longer segfaults, but it says:
Warning: JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0
