### ISSUE TITLE
Incorporate opaque identifier for the entity received in ConnectReply in linking metadata

### ISSUE THREAD

**Issue by misiekn** [newrelic/newrelic-php-agent#417]
As a PHP Agent I want to incorporate (as needed) opaque identifier for the entity received in ConnectReply in linking metadata in order to better link APM and Log data.

Part of #412 

Subtasks:
 * [X] Verify daemon accepts opaque identifier for the entity in collector response, and passes it to the agent
* [X] Verify existing agent code and add additional agent code changes as needed to use entity identifier, received from daemon, in get_linking_metadata() API for newrelic-monolog-enricher to append it to log records that are forwarded to NR1 with external log forwarder

**Comment by mfulb** [comment]
Built a test environment where I switched the daemon to report it supports P17.
Verified on connection the collector response now contained the `entity_guid` field.
Used a small test PHP application to verify the `entity.guid` showed up in the return value from the API call `newrelic_get_linking_metadata()`:

linking data = {
"entity.name":"PHP APP",
"entity.type":"SERVICE",
"entity.guid":"NDMyNTA3fEFQTXxBUFBMSUNBVElPTnwxNDM5MDc4Ng",
"hostname":"0275d2fd4bfd",
"trace.id":"e030d43b30d94941",
"span.id":"6eb1d091165a6364"
}

These are the fields required for linking data to a trace/entity.
