### ISSUE TITLE
MUST Agent reads environment variables to pass to the daemon to populate the NEW p17 metadata field of the connect request message.

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#438]
Please see MMF document for further details and links.

MUST Agent reads environment variables to pass to the daemon to populate the NEW p17 metadata field of the connect request message.

Acceptance criteria
- [x] PR with code changes is created
- [x] There are tests that cover code changes
- [x] CI PR build passes
- [x] Code is reviewed by at least 2 team members (3 team members for more complex tickets)
- [x] Code is merged into dev branch

Note: See [go repo](https://github.com/newrelic/go-agent) for reference: https://github.com/newrelic/go-agent/search?q=NEW_RELIC_METADATA_

**Comment by mfulb** [comment]
[PR 464](https://github.com/newrelic/newrelic-php-agent/pull/464) addresses this issue.
