### ISSUE TITLE
MUST APM Agent Tags (Labels) are sent to the UI.

### ISSUE THREAD

**Issue by zsistla** [newrelic/newrelic-php-agent#439]
Please see MMF document for further details and links.

Verify/ensure labels/tags show and spec functionality covered with protocol 17 enabled.
This ticket will ensure labels are now queryable in NR1.  If not either a PR or additional ticket(s) will be created based on findings.

MUST APM Agent Tags (Labels) are sent to the UI.

Acceptance criteria
- [x] Ticket is closed with findings and / or PR with code changes is created and/or ticket(s) created
- [ ] There are tests that cover any code changes
- [ ] CI PR build passes if code changes
- [ ] If code changes, code is reviewed by at least 2 team members (3 team members for more complex tickets)
- [ ] If code changes, code is merged into dev branch

Note: Do a recursive grep in the axiom, agent, and src/newrelic directories to see the full “labels” functionality.

**Comment by misiekn** [comment]
After adding a few labels in newrelic.ini as described [here](https://docs.newrelic.com/docs/apm/agents/php-agent/configuration/php-agent-configuration) following was observed:

1. Labels are visible in connect payload in newrelic-daemon.log
```
2022/05/11 16:33:28.119830 (594046) Debug: command='connect' url='collector-endpoint/agent_listener/invoke_raw_method?license_key=d9..c1&marshal_format=json&method=connect&protocol_version=16' payload={
   [
       {
           ...
           "settings": {
               ...
               "newrelic.labels": "label_type1:label_type1_value1;label_type2:label_type2_value1",
               ...
           },
           ...
       }
  ]
```
3. Labels are visible in New Relic UI when clicking on tag icon next to APP_NAME on Explorer / Services - APM / APP_NAME screen
4. After updating collector protocol to version 17, It is possible to group NRQL results by label value as described [here](https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/core-concepts/use-tags-help-organize-find-your-data/#query-tags)
5. Labels functionality test coverage
- `axiom/tests/test_cmd_appinfo.c` - tests `nr_app_info_t.labels` flatbuffers encode/decode
- `axiom/tests/test_labels.c` - `tests axiom/util_labels.c`:
-- label parsing (`nr_labels_parse`)
-- label formatting (`nr_labels_connector_format`); uses cross agents test data from `cross_agent_tests/labels.json`
- `src//newrelic/app_test.go` - tests `src/newrelic/App.go`
