### ISSUE TITLE
PHP 8 - Address Apache naming changes

### ISSUE THREAD

**Issue by kneitinger** [newrelic/newrelic-php-agent#44]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

The naming scheme of the Apache module has changed from `php7_*` to `php_*`.  Account for this when PHP 8 headers are used.

## Desired Behavior

- Apache based applications are correctly instrumented on PHP 8 machines.
  - Easiest test would be to use the php8/apache docker images, and pull up `phpinfo`
- Older versions of PHP continue to function correctly.

**Comment by Fahmy-Mohammed** [comment]
Verified on PHP 7 and 8. No code changes needed for the agent. The Apache module name is resolved automatically.
