### ISSUE TITLE
No web transaction data on Laravel 8

### ISSUE THREAD

**Issue by esbenp** [newrelic/newrelic-php-agent#45]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Hi,

We have upgrade our Laravel application to version 8 and are using Newrelic agent v. 9.14.0.290-14bb02701b5c. We are currently not seeing any web transactions. Is that because the agent does not support Laravel 8 yet? We do get non-web transactions reported

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Ubuntu 16.04.3 LTS
Php 7.4
Laravel 8.16.0

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by Fahmy-Mohammed** [comment]
Hi @esbenp. Yes, you are right, the PHP agent hasn't yet added support for Laravel 8. We are looking into adding support for this in the future. Here's a [list of frameworks](https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements#frameworks) that are currently supported.

**Comment by carltondickson** [comment]
Is Laravel 8 not officially supported? I can't see it in the list here https://docs.newrelic.com/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements/#frameworks

Seeing an issue on the new UI that clicking a transaction in the format "Controller@action" the application throws an "Oops! Something went wrong." error message...clicking on a named route, e.g. "shop.login" this work fine and get transaction information.

**Comment by Ak-x** [comment]
Hello, could you please try this issue again with the latest version of the NR agent; if the issue persists we will re-open this as a bug.
