### ISSUE TITLE
Extended Redis support

### ISSUE THREAD

**Issue by tillkruss** [newrelic/newrelic-php-agent#470]
## Summary

It seems that the `Redis` extension has only minimal support:

https://github.com/newrelic/newrelic-php-agent/blob/8536ad58490a3ad16b5cf675b1a62dddd99c532b/agent/php_internal_instrument.c#L3029-L3056

Several critical functions, such as `MULTI` transactions or `EVAL` script don't even show up.

## Desired Behavior

Support the majority of PhpRedis methods.

## Additional context

Related to #130

**Comment by tillkruss** [comment]
Ping @michael-grunder.

**Comment by michael-grunder** [comment]
From a quick glance, it looks pretty straightforward to add methods.  I can create a PR that adds them if it's something that might be merged.

**Comment by ZNeumann** [comment]
Thanks for the offer @michael-grunder ! A PR would be a big help and our team would be eager to help however we can.

**Comment by michael-grunder** [comment]
I added nearly all PhpRedis methods that actually communicate with Redis, and also sorted the wrappers to make it easier to add new methods in the future.

Redis (and PhpRedis) have a great many commands so we can also add fewer of the more commonly used methods if that is preferable.

**Comment by misiekn** [comment]
@tillkruss @michael-grunder Closing this issue - #481 will be included in next release. Thank you for your contribution! ❤️
