### ISSUE TITLE
warning: nr_php_get_environment_variables: Unable to access environmental variables on 10.1.0.313

### ISSUE THREAD

**Issue by Roze** [newrelic/newrelic-php-agent#537]
After upgrading to New Relic Version 10.1.0.313 (from 9.21.0.311) I am getting constant warning logs in the php agent log:

```
2022-09-22 15:35:52.417 +0300 (50083 50083) warning: nr_php_get_environment_variables: Unable to access environmental variables.
2022-09-22 15:35:54.420 +0300 (50089 50089) warning: nr_php_get_environment_variables: Unable to access environmental variables.
```
PHP version 8.0.23.

Is there something wrong with my php and/or NR extension ini settings I need to look at/change?

**Comment by zsistla** [comment]
Hi @Roze , apologies for the confusion and thanks for bringing this to our attention.
There is nothing wrong with php and/or the NR extension.
With the latest agent, we added the functionality for some values to be configured via environmental variables.
If no environmental variables exist, that is NOT an issue as all settings are configured as normal from the INI file.
We agree, the "warning" designation is misleading, and and the msg will be changed to not be a warning and to occur less frequently.

**Comment by Roze** [comment]
Thank you for clarification.
