### ISSUE TITLE
Magento2 - Soap Naming does not work in Version >=2.3.2

### ISSUE THREAD

**Issue by steven-hoffman-jomashop** [newrelic/newrelic-php-agent#55]
Magento2 - Soap Naming does not work in Version >=2.3.2

## Description
Magento2 - Soap Naming does not work in Version >=2.3.2
Version 2.3.2 changed the call path for the Soap Handler from `_prepareRequestData` to `prepareOperationInput`
The new request path does not call the instrumented method.
- https://github.com/newrelic/newrelic-php-agent/blob/5a9a85505ca2f94757b349f04ba9750fe8e50bdf/agent/fw_magento2.c#L373-L374
- Magento2 Current Code in [Handler.php](https://github.com/magento/magento2/blame/2.4.1/app/code/Magento/Webapi/Controller/Soap/Request/Handler.php#L146)
- Commit the introduced the regression [365b9410827529ce6e8f7fded489ffcd132706a8f8dd9e5c7548777a416bfcac](https://github.com/magento/magento2/commit/c834a1198ac0f41a14c2f7856171744644b7c4a9#diff-365b9410827529ce6e8f7fded489ffcd132706a8f8dd9e5c7548777a416bfcacR146)

## Steps to Reproduce
- Install Agent
- Install Magento2
- Make any Soap Call (eg: integrationAdminTokenServiceV1)

## Expected Behavior
Expected:
- Naming to match service (eg: WebTransaction/Action/Webapi/Soap/Magento\Integration\Api\AdminTokenServiceInterface/createAdminAccessToken; or so)

Actual:
- /FrontController/Magento\Webapi\Controller\Soap\Interceptor

## Relevant Logs / Console output
NONE

## Your Environment
Magento2 Version >= 2.3.2
Current PHP Agent

## Additional context
Looking over the C code, it should be possible to wrap `prepareOperationInput `in a similar manner to `_prepareRequestData`.

The parameters to `prepareOperationInput` are about the same as the ones for `_prepareRequestData`.
Both contain `serviceClass` and `serviceMethod`; `prepareOperationInput` wraps the `serviceMethod` inside an array.
You can see this [here](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Webapi/Controller/Soap/Request/Handler.php#L187) as _prepareRequestData delegates to prepareOperationInput.

**Comment by zsistla** [comment]
Apologies for our overactive stalebot, we are currently working on this issue.

**Comment by joshuabenuck** [comment]
Version 9.16 of the PHP agent has been [released](https://github.com/newrelic/newrelic-php-agent/releases/tag/v9.16.0.295). It includes the fix for this defect.
