### ISSUE TITLE
PHP 8.0: 64-bit musl build

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-agent#59]
## Summary

We need 64-bit musl builds of the PHP 8.0 agent. This ticket is part of issue #32.

## Desired Behavior

* Testing is done on the platform to ensure the agent builds cleanly.
* Our jenkins alpine AMIs are updated to build PHP 8.0.

## Pre-reqs and dependencies

* The nrlamp ticket as PHP 8.0 will not build without a newer version of libxml.
* This is one of the tickets that will block the completion of the tickets to update the jenkins jobs.

## Additional context

See the [MMF](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy) doc for more details.

**Comment by zsistla** [comment]
For future work after this MMF:

PHP alpine images that can eventually be looped into GHA workflow matrix. like the non-musl linux builds https://hub.docker.com/_/php?tab=tags&page=2&ordering=last_updated&name=alpine

**Comment by kneitinger** [comment]
Somehow missed closing this ticket.  This work was completed early 2021.
