### ISSUE TITLE
PHP 8.0: Update primary jobs

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-agent#61]
## Summary

Our primary jenkins jobs need to be updated to include a PHP 8.0 build of the agent. This ticket is part of issue #32.

## Desired Behavior

* The `main` and `big change` jobs include a PHP 8.0 build of the agent.

## Pre-reqs and dependencies

* Requires that all platforms be updated to build PHP 8.0 to be completed, but should be able to incrementally add platforms to this as they are updated.

## Additional context

See the [MMF](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy) doc for more details.

**Comment by joshuabenuck** [comment]
`make/release.mk` contains the targets for building the agent against all supported PHP versions. We could add additional clauses here or choose to integrate the PHP 8.0 builds later in the build process (which may require less intricate changes).

**Comment by zsistla** [comment]
The `bigchange` and `release` jobs were both [updated](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.t14oufcfupy6) and builds from GHA and Jenkins are collated properly in packages and tarballs.
