### ISSUE TITLE
PHP 8.0: Update PR job

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-agent#62]
## Summary

Our PR jenkins job needs to be updated to include a PHP 8.0 build of the agent. This ticket is part of issue #32.

## Desired Behavior

* The PR job builds and test a PHP 8.0 version of the agent.
* The building and testing occurs on 32-bit libc, 64-bit libc, 64-bit musl, and 64-bit FreeBSD targets.

## Pre-reqs and dependencies

* 32-bit and 64-bit libc PHP 8.0 agent builds
* 64-bit musl AMI updates
* 64-bit FreeBSD AMI updates

## Additional context

See the [MMF](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy) doc for more details.

**Comment by joshuabenuck** [comment]
The pull request jobs build and test the agent for a single architecture / OS target. They run `make agent-clean`, `make integration`, and either `make agent-valgrind` or `make agent-check`.

This may be the easiest of the Jenkins jobs to add support for PHP 8.0. We just need the ability to build PHP 8.0 on either an AMI or via GHA. The GHA PR job could be kept completely on the GitHub side. There's no need to have Jenkins kick it off. The Jenkins side of the job would then be used solely to build and test on platforms that are still using our legacy AMI based build nodes.

**Comment by Fahmy-Mohammed** [comment]
PHP 8 Jenkins job now contains only FreeBSD and Alpine. The libc builds are done in GHA.
