### ISSUE TITLE
PHP 8.0: 32-bit and 64-bit libc builds

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-agent#65]
## Summary

We need 32-bit and 64-bit libc builds of the PHP 8.0 agent. This ticket is part of issue #32.

## Desired Behavior

* Testing is done on the platform to ensure the agent builds cleanly.
* A GitHub Actions action exists to build each on each of the libc variants.
* The actions use official PHP 8.0 docker images to perform its build.
* A GitHub Actions workflow exists that will publish artifacts suitable for inclusion in our existing jenkins builds.

## Pre-reqs and dependencies

* This is one of the tickets that will block the completion of the tickets to update the jenkins jobs.
* See the MMF doc for details on the research / prototyping that was done.
* If the artifacts produced by this build are not usable on the CentOS versions used by our automated tests, we may need to fall back and build on our CentOS 5 build machines until we can migrate those tests to run on a newer OS. (Refer to the MMF doc for details on which libraries need to be updated in that case).

## Additional context

See the [MMF](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy) doc for more details.

**Comment by zsistla** [comment]
Please see PR #88 .
