### ISSUE TITLE
PHP 8.0: Jenkins GitHub Actions trigger

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-agent#66]
## Summary

We need the ability to setup a jenkins proxy job that can trigger a GitHub Actions workflow and wait for it to complete. This ticket is part of issue #32.

## Desired Behavior

* A script exists that will trigger a named GitHub Actions workflow on a specified git commit hash and wait for it to complete.
* The pass / fail state of the jenkins job accurately reflects the pass / fail state of the GitHub Actions workflow.
* Optional: The script also calls the artifact pull script once the build is complete (as the whole purpose of triggering a GitHub Actions workflow in this MMF is to generate artifacts for use by child jobs in jenkins).

## Pre-reqs and dependencies

* This can be created using our existing ubuntu based workflow as an initial target.
* This script is needed in by the PR and inward singing jobs so they can trigger the build of the PHP 8.0 agent.

## Additional context

See the [MMF](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy) doc for more details.

**Comment by zsistla** [comment]
Please see PR: https://source.datanerd.us/php-agent/newrelic-php-agent-internal/pull/17

**Comment by zsistla** [comment]
See [PR](https://source.datanerd.us/php-agent/newrelic-php-agent-internal/pull/17).
