### ISSUE TITLE
PHP 8.0: GitHub Actions artifact pull script

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-agent#67]
## Summary

We need the ability to pull artifacts from a GitHub actions workflow. This ticket is part of issue #32.

## Desired Behavior

* A script exists that will pull artifacts from a targeted GitHub workflow. The script must be able to filter the targeted workflows by artifact name and git commit hash.

## Pre-reqs and dependencies

* A prototype of this script that pulls against one of the prototype builds exists that can be used as a starting point. See the MMF doc (linked below) for more details.
* This script will be needed by most of our top-level jenkins jobs in order to retrieve the PHP 8.0 builds for 32-bit libc and 64-bit libc.

## Additional context

See the [MMF](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy) doc for more details.

**Comment by zsistla** [comment]
See [PR](https://source.datanerd.us/php-agent/newrelic-php-agent-internal/pull/17).
