### ISSUE TITLE
Excessive notices with Drupal 10

### ISSUE THREAD

**Issue by neclimdul** [newrelic/newrelic-php-agent#682]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

NewRelic is currently generating Gigs of logs just running our site. Its all notices that look like this:

```
2023-06-18 02:39:25.321 +0000 (125 125) info: Drupal 8: cannot get zend_function entry for Drupal\Core\Extension\ModuleHandler::getimplementations
2023-06-18 02:39:25.321 +0000 (125 125) info: Drupal 8: cannot get zend_function entry for Drupal\Core\Extension\ModuleHandler::implementshook
```

These methods have been removed from Drupal 10 so this code seems to be causing the notices:
https://github.com/newrelic/newrelic-php-agent/blob/f5f0661c05500230cb88a5751c8e26013147a151/agent/fw_drupal8.c#L468-L471

## Steps to Reproduce

Run newrelic with Drupal 10. Inspect /var/log/newrelic/php_agent.log

## Expected Behavior

Quiet logs.

## Relevant Logs / Console output

In description.

## Your Environment

Drupal 10.1
php 8.1.20
newrelic-php5-10.10.0.1-linux-musl

## Additional context

https://www.drupal.org/node/3000490
Work around is to turn down logging.

**Comment by ZNeumann** [comment]
Hello, thanks for the detailed explanation. The amount of logging can be reduced by setting the [newrelic.loglevel ini](https://docs.newrelic.com/docs/apm/agents/php-agent/configuration/php-agent-configuration/#inivar-loglevel) value to either `warning` or `error`.

**Comment by neclimdul** [comment]
Yes thank you. I forgot to mention I used that as a workaround for the bug.

**Comment by ZNeumann** [comment]
This has been addressed in https://github.com/newrelic/newrelic-php-agent/pull/685 and will be included in our next release. Please continue to use the workaround in the meantime.
