### ISSUE TITLE
Unhandled Unhandled Promise Rejection: Failed to fetch

### ISSUE THREAD

**Issue by vekien** [newrelic/newrelic-php-agent#697]
## Description

Hello, at my company we have the latest NR PHP Agent and we also have Sentry running, everything has been fine and dandy for well over a year.

Since last week we have started to see the following error in Sentry, a lot:

```
exception
TypeError: Unhandled Promise Rejection: Failed to fetch
Error fetch POST https://bam.eu01.nr-data.net/resources/1/NRJS-xxx?a=xxx&v=1.236.0&to=xxx%3D%3D&rst=18229&ck=0&s=xx&ref=xxx&st=1689955074052
```

We are wondering if this is an issue with NR? It only happens when it tries to "fetch" against `nr-data`, `xhr` post requests do not error.. It is not 100%, but enough where we have over a thousand reports over the past 7 days. 

The issue is originating from the file: https://js-agent.newrelic.com/async-api.30bd804e-1.236.0.min.js

## Steps to Reproduce

Not sure I can really provide this as it's inconsistent (but happens for a lot of users) and looks to just be basic "Add PHP Agent and allow Browser Monitoring"

## Expected Behavior

I don't expect this error to happen, it did not happen prior to about a week ago.

## Relevant Logs / Console output

(n/a)

## Your Environment

It's a ECS Docker PHP Env, it happens on all browsers and all operating systems.

## Additional context

(n/a)

**Comment by vekien** [comment]
This looks to be the same as https://github.com/newrelic/newrelic-browser-agent/issues/599

**Comment by lavarou** [comment]
@vekien I confirmed that the New Relic PHP Agent 10.19.0.9 injects the latest Browser Agent (as of today 1.258.0). If this issue still exists, please please follow [these steps](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/#file-ticket) to create a support case, where a member of our New Relic Support Team will work with you to gather the necessary information securely and help debug your issue. If your subscription level does not include technical support, the other option available is to use New Relic’s community support channel: [Explorers Hub](https://forum.newrelic.com/s/). From there, a member of our New Relic Support Team will work with you to gather the necessary information securely and help debug your issue.
