### ISSUE TITLE
Use transaction id on start_transaction / stop_transaction()

### ISSUE THREAD

**Issue by arku31** [newrelic/newrelic-php-agent#74]
## Summary

Are there any plans to add any kind of transaction identifier in start_transaction()\end_transaction()?
In the current implementation, there is only boolean being returned and this means that we cannot finish an exact transaction and only have to believe that by calling end_transaction() it will stop the one we want. It works in a typical PHP application as it is single-threaded but doesn’t work when it comes to applications that stay in-memory (either CLI or web).
F.e. in C implementation, on start transaction it returns a pointer to the transaction that can be used later to stop exactly this one transaction. 

## Possible Solution

Return any kind of identifier. Either string with id or just a pointer to the transaction.

## Additional context

We have two use cases where it is important: swoole based web API and CLI based multi-thread application

**Comment by ak-war** [comment]
We plan to explore async use cases in the future, not making any changes at this time.

**Comment by marcoscoelho** [comment]
hello, I came from the future, we need support for this problem.
