### ISSUE TITLE
How to get monolog `$context`?

### ISSUE THREAD

**Issue by jamesmehorter** [newrelic/newrelic-php-agent#741]
## Summary

When we log a message with context data, that context data is not present on the log entry in New Relic.

We use Laravel, e.g. `Log::info('a log message', [ 'some' => 'helpful debugging data' ]);`. Under-the-hood, this is passed to monolog as `addRecord(6, 'a log message', [ 'some' => 'helpful debugging data' ]);`

See
* https://github.com/Seldaek/monolog/blob/main/src/Monolog/Logger.php#L320-L409
* https://laravel.com/docs/10.x/logging#contextual-information

However, if we send both the message and context as a JSON string in the message, the context is parsed by New Relic and log attributes are created. E.g. `Log::info(json_encode(['message' => 'a log message', 'some' => 'helpful debugging data' ]));`

## Desired Behavior
Context data supplied with a log entry is available as attributes in New Relic without the need of rewriting all `Log::` entries in our codebase.

**Comment by jamesmehorter** [comment]
I found `HAVE_CONTET_IN_MESSAGE` here https://github.com/newrelic/newrelic-php-agent/blob/main/agent/lib_monolog.c#L158 and am curious if this is related? 

It's curious because, it seems that bool is hardcoded to `0` (disabled?). https://github.com/newrelic/newrelic-php-agent/blob/main/agent/lib_monolog.c#L31-L41

**Comment by Huluti** [comment]
Should be fixed with https://github.com/newrelic/newrelic-php-agent/pull/753?

**Comment by Huluti** [comment]
On my side with Symfony with automatic log forwadding I have just unuseful logs

![image](https://github.com/newrelic/newrelic-php-agent/assets/5782198/d55edbed-7c0c-4850-821a-6d5f9edfffba)

**Comment by Huluti** [comment]
Thanks for your answer! But why prefer using an external tool if New Relic has its own log forwarder? Placeholder is a native monolog feature, so it would make sense to support it no?

**Comment by jamesmehorter** [comment]
@Huluti I wonder if your comment is more appropriate on https://github.com/newrelic/newrelic-php-agent/issues/742? I.e. Does monolog us a processor to perform the find/replace of placeholders?

**Comment by tsantos84** [comment]
> @Huluti I wonder if your comment is more appropriate on #742? I.e. Does monolog use a processor to perform the find/replace of placeholders?

Hello everyone. Yes, Monolog does have a [processor](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Processor/PsrLogMessageProcessor.php) to replace placeholders by its values defined in context. Resolving the issue #742 you've opened will fix @Huluti 's [comment](https://github.com/newrelic/newrelic-php-agent/issues/741#issuecomment-1786057758)
