### ISSUE TITLE
New Relic is causing PHP Deprecated Notices on PHP 8.1 and WordPress 6.3.2

### ISSUE THREAD

**Issue by ParhamG** [newrelic/newrelic-php-agent#759]
After switching to PHP 8.1, we are seeing our logs filled out with PHP Deprecated notices for our WP 6.3.2 app with messages like this:

```
PHP Deprecated:  mysqli_real_connect(): Passing null to parameter #5 ($database) of type ?string is deprecated in /wordpress-versions/6.3.2/wp-includes/class-wpdb.php:2035
PHP Deprecated:  mysqli_real_connect(): Passing null to parameter #6 ($port) of type ?int is deprecated in /wordpress-versions/6.3.2/wp-includes/class-wpdb.php:2035
PHP Deprecated:  mysqli_real_connect(): Passing null to parameter #7 ($socket) of type ?string is deprecated in /wordpress-versions/6.3.2/wp-includes/class-wpdb.php:2035
```

We have confirmed that disabling the New Relic agent makes these go away.

PHP version: 8.1.25
WordPress: 6.3.2
New Relic Version: 10.13.0.2

Possibly related ticket: #457

**Comment by ZNeumann** [comment]
Hi @ParhamG , this has been resolved by https://github.com/newrelic/newrelic-php-agent/pull/750 and the fix will be included in the next release of the PHP Agent.
