### ISSUE TITLE
Support for PHP Framework Yii2

### ISSUE THREAD

**Issue by razvanphp** [newrelic/newrelic-php-agent#821]
Hello,

I see that in the documentation of the agent it's stated that Yii 1.x support is built-in for automatic framework detection, but we've noticed that for Yii 2 this is not the case.

To give you some context about this, Yii 2.0 was released in Oct 2014 and it's been well maintained since then to be a reputable PHP framework used in (many) production deployments.

Yii 1.1 end of life was declared since 2023, but it still receives  security updates from the community till 2026.

Since the integration extensions are not so great and have low quality of code, was wondering if it would be possible to develop the framework detection in the Newrelic Agent for everybody, I'm sure the community would love that.

Can we support somehow with the testing and implementation? Are contributions welcome for this? I could probably do it myself with some guidance and testing support.

PS: we also sent this internally through support, Feature Request ID: NR-158719

Thank you in advance!
R

**Comment by razvanphp** [comment]
For reference, here is the current detection trigger code:
https://github.com/newrelic/newrelic-php-agent/blob/320ea571a11bc469d7d8179dfe51577b54df11df/agent/fw_yii.c#L84-L89

This is the referenced source code from Yii1: 
- https://github.com/yiisoft/yii/blob/master/framework/web/actions/CAction.php#L70
- https://github.com/yiisoft/yii/blob/master/framework/web/actions/CInlineAction.php#L41

In Yii2, the Action class is renamed to:
- https://github.com/yiisoft/yii2/blob/master/framework/base/Action.php#L82
- https://github.com/yiisoft/yii2/blob/master/framework/base/InlineAction.php#L49

The `getController()` and `getId()` functions still exist in `$this` context, so everything should still work.

The only features still missing from both detections would be to append the module id to the Transaction name (optional) and have another detection for CLI commands as non-Web transactions.

Please let me know if I can provide more information for fixing this.

**Comment by razvanphp** [comment]
Discovered also that the path here:
https://github.com/newrelic/newrelic-php-agent/blob/320ea571a11bc469d7d8179dfe51577b54df11df/agent/php_execute.c#L415-L416
Would also work for Yii2, only if the comparison is Case Insensitive, as the file is now [named](https://github.com/yiisoft/yii2/blob/master/framework/Yii.php) `Yii.php`

The biggest problem is that currently the ErrorHandler is not wrapped at all, so no errors are displayed in NewRelic... 
I can see for other frameworks that this is implemented:
https://github.com/newrelic/newrelic-php-agent/blob/320ea571a11bc469d7d8179dfe51577b54df11df/agent/fw_laravel.c#L573

**Comment by lavarou** [comment]
@razvanphp Thank you for providing the details of changes in Yii2 and [your contribution](#823). Our team is actively looking into incorporating these updates in one of the upcoming agent release.

**Comment by razvanphp** [comment]
I can confirm that this works with the official version of PHP agent now.
