### ISSUE TITLE
Segfault encountered - causing intermittent 502 response errors

### ISSUE THREAD

**Issue by garbetjie** [newrelic/newrelic-php-agent#92]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I'm not sure if this is the right place to raise this, or whether the community discussion boards would be better.

As mentioned in the title, it appears as if the New Relic agent is causing segfaults intermittently. I can't seem to figure out what could be causing the issue, but the one function that keeps coming up is `opcache_get_status()`.

It appears to only segfault after the daemon has connected to New Relic. After the initial page load, keep refreshing and you should eventually encounter a 502 status page.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

I have created a Docker image that provides a reproducible way of experiencing the issue. Steps are outlined below:

1. Pull the Docker image `garbetjie/php:7.4-newrelic-debug`.

2. Run this image using the following command: `docker run -e NEWRELIC_ENABLED=true -e NEWRELIC_LICENCE=XXX -e NEWRELIC_LOGLEVEL=verbosedebug -e NEWRELIC_DAEMON_LOGLEVEL=verbosedebug -e OPCACHE_ENABLED=false garbetjie/php:7.4-newrelic-debug`. Replace `NEWRELIC_LICENCE=XXX` with the actual licence value.

3. If you want to enable opcache, change `-e OPCACHE_ENABLED=false` to `-e OPCACHE_ENABLED=true`.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

I expected that every request would execute successfully, without any server errors.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

```
2021-02-01 17:47:42.600 +0000 (78 78) debug: 'WT_IS_FILENAME & SCRIPT_FILENAME' naming is '/phpinfo.php'
Process 78 (version 9.15.0.293) received signal 11: segmentation violation
process id 78 fatal signal (SIGSEGV, SIGFPE, SIGILL, SIGBUS, ...)  - stack dump follows (code=0x7f021bfce000 bss=0x7f021c2c987c):
No backtrace on this platform.
PHP execution trace follows...
#0 opcache_get_status()
#1 unknown()
```

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

* PHP 7.4 FPM running in a Docker container based on Alpine Linux.
* New Relic version 9.15.0.293.

[TIP]:  # ( Include as many relevant details about your environment as possible. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by joshuabenuck** [comment]
@garbetjie Yes, this is the right place to raise the issue.

I tried running the docker image using the command you provided, but it seems to hang. Would you be able to share the `Dockerfile` you used to create your image? That would allow me to build it locally and better understand how it is setup. I expect I'll want to modify it a bit to enable additional debugging options as I look into what is causing the segfault.

**Comment by garbetjie** [comment]
@joshuabenuck Thanks for the feedback.

Apologies that the Docker image didn't work for you. I've created a separate repository at https://github.com/garbetjie/docker-php-newrelic-segfault that contains everything that should be needed to replicate it. There are some notes in the README file in that repo about how I've attempted to produce the issue.

Building the image shouldn't take any more than a `docker build -t tag:latest .`. Running it just requires two environment variables, documented in the README.

Please let me know if there's anything more I can provide you with to help resolve this.

**Comment by joshuabenuck** [comment]
@garbetjie Thank you for setting up that repo (and for the clear explanation of the problem / self-contained repro example)! It greatly simplified and accelerated the troubleshooting process. Issues like this often take quite a while to track down otherwise.

Here's a back trace of the segfault:
```
#0  0x000056385b99c0d3 in zend_hash_find ()
#1  0x00007fb39e3d812c in opencensus_trace_execute_internal ()
   from /usr/local/lib/php/extensions/no-debug-non-zts-20190902/opencensus.so
#2  0x000056385b97bc67 in zend_call_function ()
#3  0x000056385b97bd35 in _call_user_function_ex ()
#4  0x00007fb39e40a97e in nr_php_call_user_func ()
    at /home/hudson/workspace/php-release-agent/label/alpine-3-3-1/agent/php_call.c:49
#5  0x00007fb39e4121af in nr_php_user_instrumentation_from_opcache ()
    at /home/hudson/workspace/php-release-agent/label/alpine-3-3-1/agent/php_execute.c:1458
#6  0x00007fb39e42bf79 in nr_php_txn_begin ()
    at /home/hudson/workspace/php-release-agent/label/alpine-3-3-1/agent/php_txn.c:852
#7  0x00007fb39e429bc1 in zm_activate_newrelic ()
    at /home/hudson/workspace/php-release-agent/label/alpine-3-3-1/agent/php_rinit.c:99
#8  0x000056385b98efc0 in zend_activate_modules ()
#9  0x000056385b92a156 in php_request_startup ()
```
This app has both newrelic and opencensus installed. This is [not a supported scenario](https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements#other-monitoring-software). Extensions that capture function traces in PHP usually conflict with one another given how deeply they hook into the PHP runtime. I believe that to be the case here due to both opencensus and newrelic tracing calls being present in the back trace.

As far as why you only see this when multiple PHP-FPM processes are in use, shared memory issues don't tend to show up until you start running more than one process. We've seen that with just the newrelic extension in use. The chances of seeing a conflict only go up as you add additional tracing extensions to the mix.

Out of curiosity, what is leading to the desire to enable both newrelic and opencensus in a single application?

Disabling one or the other extension is likely the best path forward here.

**Comment by garbetjie** [comment]
Hey @joshuabenuck.

Thank you so much for taking the time to investigate this. I must have missed the disclaimer about multiple APMs.

The Docker image that I'm using is kind of a "all-in-one" toolkit, and has multiple useful extensions compiled and available for developers to use. So it's not necessarily that I have a _desire_ to use opencensus - it's more that it's there & available.

The reason I came across this issue is because I make use of New Relic for running services in production. However, I had forgotten that opencensus was enabled, and couldn't figure out why New Relic wasn't working.

I'll definitely be disabling opencensus then.

Thank you again for the quick debugging & response!
