### ISSUE TITLE
Virtuoso: First PHP Recipes

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-php-agent#93]
For users of Debian or RHEL derived systems, running PHP under FPM with Apache or nginx, the New Relic Open Install Library can be used to easily install and configure the PHP Agent on their systems.

**Comment by Fahmy-Mohammed** [comment]
All work contained in the [PHP feature branch](https://github.com/newrelic/open-install-library/pull/405) is now deployed.
