### ISSUE TITLE
SEGFAULT when upgrading agent from 10.4.0.316-30f9fca2e3e7 to 10.22.0.12-687e42d2e365 PHP8.1

### ISSUE THREAD

**Issue by blueprismo** [newrelic/newrelic-php-agent#941]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When I update the agent in my instance with php8.1  from `10.4.0.316-30f9fca2e3e7` to `10.22.0.12-687e42d2e365` whenever I run (for example) `php artisan` command i get a segmentation fault.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
Update an agent from `10.4.0.316` to `10.22.0.12` .

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
All works fine without segfaults.

## Relevant Logs / Console output
I captured this with `gdb`:
```gdb
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8d0e91cc60 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007f8d0e91cc60 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f8d0e91e78b in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f8d1092e2c6 in __GI___backtrace (array=<optimized out>, size=<optimized out>) at backtrace.c:116
#3  0x00007f8d0bdcf421 in nr_signal_tracer_common () at util_signals.c:113
#4  0x00007f8d0bd9dc2d in nr_php_fatal_signal_handler () at /usr/local/src/newrelic-php-agent/agent/php_minit.c:738
#5  <signal handler called>
#6  0x00007f8d00000001 in ?? ()
#7  0x000055937c350081 in ?? ()
#8  0x000055937c2f6d90 in ?? ()
#9  0x000055937c31e317 in execute_ex ()
#10 0x000055937c0ea21c in ?? ()
#11 0x000055937c0eb218 in ?? ()
#12 0x000055937c2a8c3c in zend_call_function ()
#13 0x000055937c2a900d in zend_call_known_function ()
#14 0x000055937c1a8287 in ?? ()
#15 0x000055937c2a7ecc in zend_lookup_class_ex ()
#16 0x000055937c2a91fd in zend_fetch_class ()
#17 0x000055937c2d484e in ?? ()
#18 0x000055937c31eb6e in execute_ex ()
#19 0x000055937c0ea21c in ?? ()
#20 0x000055937c0eb218 in ?? ()
#21 0x000055937c0ea21c in ?? ()
#22 0x000055937c0eb218 in ?? ()
#23 0x000055937c0ea21c in ?? ()
#24 0x000055937c0eb218 in ?? ()
#25 0x000055937c0ea21c in ?? ()
#26 0x000055937c0eb218 in ?? ()
#27 0x000055937c0ea21c in ?? ()
#28 0x000055937c0eb218 in ?? ()
#29 0x000055937c0ea21c in ?? ()
#30 0x000055937c0eb218 in ?? ()
#31 0x000055937c0ea21c in ?? ()
#32 0x000055937c0eb218 in ?? ()
#33 0x000055937c0ea21c in ?? ()
#34 0x000055937c0eb218 in ?? ()
#35 0x000055937c3275fd in zend_execute ()
#36 0x000055937c2b7395 in zend_execute_scripts ()
#37 0x000055937c253f1a in php_execute_script ()
#38 0x000055937c3a050e in ?? ()
#39 0x000055937c0f5228 in ?? ()
#40 0x00007f8d10825083 in __libc_start_main (main=0x55937c0f4e20, argc=2, argv=0x7fffcd7b5948, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffcd7b5938) at ../csu/libc-start.c:308
#41 0x000055937c0f59fe in _start ()
```
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Browser name and version: n/a
* Operating System and version: Ubuntu 20.04 

## Additional context

```
root@host:/etc/php/8.1/mods-available# uname -a
Linux host 5.15.0-1062-aws #68~20.04.1-Ubuntu SMP Wed May 1 15:24:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jeffchiudev** [comment]
Hi there @blueprismo, my name is Jeff, I'm a support engineer from New Relic; I just stepped out of a meeting with our PHP engineers and they brought your issue to our attention. 

They would like to get more information, and unfortunately Git Hub isn't a secure place to share files that we'd need to continue troubleshooting your case. 

Can you please create a support case within the New Relic product support or via the New Relic forums? Once there we'll be able to securely gather information. 

Cheers!

**Comment by lavarou** [comment]
Hi @blueprismo! In order to get more information to diagnose this issue (account # and application id), we suggest filing a ticket by following the steps [here](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/#file-ticket), where we can engage our General Tech Support engineers.

If you do not have access to this support flow & the ability to open a support ticket directly, we can reach out via a post on the NR [Community Forums](https://discuss.newrelic.com/).
