### ISSUE TITLE
Degrade in my CakePHP2 application

### ISSUE THREAD

**Issue by dmnlk** [newrelic/newrelic-php-agent#997]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
After merging this PR and introducing version v11.4.0.17 into my application that uses CakePHP2, I noticed that APM processes all requests as index.php.
https://github.com/newrelic/newrelic-php-agent/pull/983

I understand that since this PR is aimed at supporting CakePHP4~5 and CakePHP2 has already reached its EOL, active support for it might not be a priority. However, is it possible to ensure that APM works correctly with CakePHP2 as well?

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
use v11.4.0.17 and cakephp2 app
[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
transaction name is collect
[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
<img width="473" alt="image" src="https://github.com/user-attachments/assets/f210ca3d-5bfc-44fe-adb6-853b1394d481" />

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version: chrome
* ex: Operating System and version: CentOS7

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by cpearcey** [comment]
I wanted to provide some details around this request.  CakePHP2 support was dropped in June of this year and was announced [here](https://forum.newrelic.com/s/hubtopic/aAX8W000000L5oMWAS/new-relic-endoflife-eol-during-q4-fy24-and-q1-fy25): last year. We cannot provide support for that version of CakePHP. If you want to use CakePHP2 to keep being instrumented, you will need to use older version of an agent that.  Please refer to the attached link for more details.

**Comment by Mat-Moo** [comment]
Which version last official supports CakePHP2 - because there is nothing in release notes to say removed.. another nail in the coffin for New Relic and PHP support
